package hypervisor

import (
	"bytes"
	"encoding/json"
	"fmt"
	"net"
	"os"
	"os/exec"
	"reflect"
	"regexp"
	"testing"

	"github.com/google/go-cmp/cmp"
	zconfig "github.com/lf-edge/eve-api/go/config"
	zcommon "github.com/lf-edge/eve-api/go/evecommon"
	"github.com/lf-edge/eve/pkg/pillar/types"
	. "github.com/onsi/gomega"
	uuid "github.com/satori/go.uuid"
	"github.com/sirupsen/logrus"
)

const (
	// DefaultUUID is the default UUID for the domain
	DefaultUUID = "e4f1c2a7-9b3d-4e5f-8a6b-2c7d9e0f1a2b"
	// DefaultDomainName is the default domain name
	DefaultDomainName = DefaultUUID + ".0.0"
)

var kvmIntel, kvmArm KvmContext
var swtpmCtrlSock = ""

// these ones are very much handcrafted just for the tests
func init() {
	kvmIntel = KvmContext{
		devicemodel: "pc-q35-3.1",
		dmExec:      "",
		dmArgs:      []string{},
	}
	kvmArm = KvmContext{
		devicemodel: "virt",
		dmExec:      "",
		dmArgs:      []string{},
	}
}

// setStaticVsockCid is a helper function to set the guest-cid to a static value
// in the resulting config file otherwise the test will fail because the guest-cid
// is incremented every time config file is generated.
func setStaticVsockCid(input []byte) []byte {
	re := regexp.MustCompile(`guest-cid\s*=\s*"\d+"`)
	out := re.ReplaceAllString(string(input), `guest-cid = "3"`)
	return []byte(out)
}

func TestCreateDomConfigOnlyCom1(t *testing.T) {
	id, err := uuid.NewV4()
	if err != nil {
		t.Errorf("NewV4 failed: %v", err)
	}
	config := types.DomainConfig{
		UUIDandVersion: types.UUIDandVersion{UUID: id, Version: "1.0"},
		VmConfig: types.VmConfig{
			Kernel:     "/boot/kernel",
			Ramdisk:    "/boot/ramdisk",
			ExtraArgs:  "init=/bin/sh",
			Memory:     1024 * 1024 * 10,
			VCpus:      2,
			VncDisplay: 5,
			VncPasswd:  "rosebud",
		},
		GPUConfig: "legacy",
		VifList: []types.VifConfig{
			{Bridge: "bn0", Mac: net.HardwareAddr{0x6a, 0x00, 0x03, 0x61, 0xa6, 0x90}, Vif: "nbu1x1"},
			{Bridge: "bn0", Mac: net.HardwareAddr{0x6a, 0x00, 0x03, 0x61, 0xa6, 0x91}, Vif: "nbu1x2"},
		},
		IoAdapterList: []types.IoAdapter{
			{Type: types.IoCom, Name: "COM1"},
		},
	}
	disks := []types.DiskStatus{
		{Format: zconfig.Format_QCOW2, FileLocation: "/foo/bar.qcow2", Devtype: "hdd"},
		{Format: zconfig.Format_CONTAINER, FileLocation: "/foo/container", Devtype: "9P"},
		{Format: zconfig.Format_RAW, FileLocation: "/foo/bar.raw", Devtype: "hdd"},
		{Format: zconfig.Format_RAW, FileLocation: "/foo/cd.iso", Devtype: "cdrom"},
		{Format: zconfig.Format_CONTAINER, FileLocation: "/foo/volume", Devtype: ""},
	}
	aa := types.AssignableAdapters{
		Initialized: true,
		IoBundleList: []types.IoBundle{
			{
				Type:            types.IoCom,
				AssignmentGroup: "COM1",
				Phylabel:        "COM1",
				Ifname:          "COM1",
				Serial:          "/dev/ttyS0",
				UsedByUUID:      config.UUIDandVersion.UUID,
			},
		},
	}
	conf, err := os.CreateTemp("/tmp", "config")
	if err != nil {
		t.Errorf("Can't create config file for a domain %v", err)
	} else {
		defer os.Remove(conf.Name())
	}

	t.Run("amd64", func(t *testing.T) {
		conf.Seek(0, 0)
		if err := kvmIntel.CreateDomConfig(DefaultDomainName, config, types.DomainStatus{},
			disks, &aa, nil, swtpmCtrlSock, conf); err != nil {
			t.Errorf("CreateDomConfig failed %v", err)
		}
		defer os.Truncate(conf.Name(), 0)

		result, err := os.ReadFile(conf.Name())
		if err != nil {
			t.Errorf("reading conf file failed %v", err)
		}

		// this is the only way to get the expected output (◔_◔)
		result = setStaticVsockCid(result)
		expected := fmt.Sprintf(`# This file is automatically generated by domainmgr
[msg]
  timestamp = "on"

[machine]
  type = "pc-q35-3.1"
  dump-guest-core = "off"
  accel = "kvm"
  vmport = "off"
  kernel-irqchip = "on"
  kernel = "/boot/kernel"
  initrd = "/boot/ramdisk"
  append = "init=/bin/sh"

[global]
  driver = "kvm-pit"
  property = "lost_tick_policy"
  value = "delay"

[global]
  driver = "ICH9-LPC"
  property = "disable_s3"
  value = "1"

[global]
  driver = "ICH9-LPC"
  property = "disable_s4"
  value = "1"

[rtc]
  base = "localtime"
  driftfix = "slew"

[device]
  driver = "intel-iommu"
  caching-mode = "on"

[overcommit]
  mem-lock = "off"

[chardev "charmonitor"]
  backend = "socket"
  path = "/run/hypervisor/kvm/%s/qmp"
  server = "on"
  wait = "off"

[mon "monitor"]
  chardev = "charmonitor"
  mode = "control"

[chardev "charlistener"]
  backend = "socket"
  path = "/run/hypervisor/kvm/%s/listener.qmp"
  server = "on"
  wait = "off"

[mon "listener"]
  chardev = "charlistener"
  mode = "control"

[memory]
  size = "10240"

[smp-opts]
  cpus = "2"
  sockets = "1"
  cores = "2"
  threads = "1"

[device]
  driver = "virtio-serial"
  addr = "3"

[chardev "charserial0"]
  backend = "socket"
  mux = "on"
  path = "/run/hypervisor/kvm/%s/cons"
  server = "on"
  wait = "off"
  logfile = "/dev/fd/1"
  logappend = "on"

[device]
  driver = "virtconsole"
  chardev = "charserial0"
  name = "org.lfedge.eve.console.0"



[device "pci.2"]
  driver = "pcie-root-port"
  port = "12"
  chassis = "2"
  bus = "pcie.0"
  addr = "0x2"

[device "usb"]
  driver = "qemu-xhci"
  p2 = "15"
  p3 = "15"
  bus = "pci.2"
  addr = "0x0"

[device "input0"]
  driver = "usb-tablet"
  bus = "usb.0"
  port = "1"


[device "pci.4"]
  driver = "pcie-root-port"
  port = "14"
  chassis = "4"
  bus = "pcie.0"
  addr = "0x4"

[drive "drive-virtio-disk0"]
  file = "/foo/bar.qcow2"
  format = "qcow2"
  aio = "io_uring"
  cache = "writeback"
  if = "none"

[device "virtio-disk0"]
  driver = "virtio-blk-pci"
  scsi = "off"
  bus = "pci.4"
  addr = "0x0"
  drive = "drive-virtio-disk0"


[fsdev "fsdev1"]
  fsdriver = "local"
  security_model = "none"
  multidevs = "remap"
  path = "/foo/container"

[device "fs1"]
  driver = "virtio-9p-pci"
  fsdev = "fsdev1"
  mount_tag = "share_dir"
  addr = "0x5"


[device "pci.6"]
  driver = "pcie-root-port"
  port = "16"
  chassis = "6"
  bus = "pcie.0"
  addr = "0x6"

[drive "drive-virtio-disk2"]
  file = "/foo/bar.raw"
  format = "raw"
  aio = "io_uring"
  cache = "writeback"
  if = "none"

[device "virtio-disk2"]
  driver = "virtio-blk-pci"
  scsi = "off"
  bus = "pci.6"
  addr = "0x0"
  drive = "drive-virtio-disk2"


[drive "drive-sata0-3"]
  file = "/foo/cd.iso"
  format = "raw"
  if = "none"
  media = "cdrom"
  readonly = "on"

[device "sata0-0"]
  drive = "drive-sata0-3"
  driver = "ide-cd"
  bus = "ide.0"

[device "pci.7"]
  driver = "pcie-root-port"
  port = "17"
  chassis = "7"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x7"

[netdev "hostnet0"]
  type = "tap"
  ifname = "nbu1x1"
  br = "bn0"
  script = "/etc/xen/scripts/qemu-ifup"
  downscript = "no"
  vhost = "on"

[device "net0"]
  driver = "virtio-net-pci"
  netdev = "hostnet0"
  mac = "6a:00:03:61:a6:90"
  bus = "pci.7"
  addr = "0x0"

[device "pci.8"]
  driver = "pcie-root-port"
  port = "18"
  chassis = "8"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x8"

[netdev "hostnet1"]
  type = "tap"
  ifname = "nbu1x2"
  br = "bn0"
  script = "/etc/xen/scripts/qemu-ifup"
  downscript = "no"
  vhost = "on"

[device "net1"]
  driver = "virtio-net-pci"
  netdev = "hostnet1"
  mac = "6a:00:03:61:a6:91"
  bus = "pci.8"
  addr = "0x0"

[chardev "charserial-usr0"]
  backend = "serial"
  path = "/dev/ttyS0"

[device "serial-usr0"]
  driver = "isa-serial"
  chardev = "charserial-usr0"

[device "eve-vsock0"]
  driver = "vhost-vsock-pci"
  disable-legacy = "on"
  guest-cid = "3"
`, DefaultDomainName, DefaultDomainName, DefaultDomainName)
		if string(result) != expected {
			t.Errorf("got an unexpected resulting config %s", string(result))
		}
	})

	config.VirtualizationMode = types.FML
	config.BootLoader = "/usr/lib/xen/boot/OVMF_CODE.fd"
	t.Run("amd64-fml", func(t *testing.T) {
		conf.Seek(0, 0)
		if err := kvmIntel.CreateDomConfig(DefaultDomainName, config, types.DomainStatus{},
			disks, &aa, nil, swtpmCtrlSock, conf); err != nil {
			t.Errorf("CreateDomConfig failed %v", err)
		}
		defer os.Truncate(conf.Name(), 0)

		result, err := os.ReadFile(conf.Name())
		if err != nil {
			t.Errorf("reading conf file failed %v", err)
		}

		result = setStaticVsockCid(result)
		expected := fmt.Sprintf(`# This file is automatically generated by domainmgr
[msg]
  timestamp = "on"

[machine]
  type = "pc-q35-3.1"
  dump-guest-core = "off"
  accel = "kvm"
  vmport = "off"
  kernel-irqchip = "on"
  kernel = "/boot/kernel"
  initrd = "/boot/ramdisk"
  append = "init=/bin/sh"

[global]
  driver = "kvm-pit"
  property = "lost_tick_policy"
  value = "delay"

[global]
  driver = "ICH9-LPC"
  property = "disable_s3"
  value = "1"

[global]
  driver = "ICH9-LPC"
  property = "disable_s4"
  value = "1"

[rtc]
  base = "localtime"
  driftfix = "slew"

[device]
  driver = "intel-iommu"
  caching-mode = "on"

[drive "drive-ovmf-code"]
  if = "pflash"
  format = "raw"
  readonly = "on"
  unit = "0"
  file = "/usr/lib/xen/boot/OVMF_CODE.fd"

[drive "drive-ovmf-vars"]
  if = "pflash"
  format = "raw"
  unit = "1"
  file = "/persist/vault/ovmf/%s_OVMF_VARS.fd"

[overcommit]
  mem-lock = "off"

[chardev "charmonitor"]
  backend = "socket"
  path = "/run/hypervisor/kvm/%s/qmp"
  server = "on"
  wait = "off"

[mon "monitor"]
  chardev = "charmonitor"
  mode = "control"

[chardev "charlistener"]
  backend = "socket"
  path = "/run/hypervisor/kvm/%s/listener.qmp"
  server = "on"
  wait = "off"

[mon "listener"]
  chardev = "charlistener"
  mode = "control"

[memory]
  size = "10240"

[smp-opts]
  cpus = "2"
  sockets = "1"
  cores = "2"
  threads = "1"

[device]
  driver = "virtio-serial"
  addr = "3"

[chardev "charserial0"]
  backend = "socket"
  mux = "on"
  path = "/run/hypervisor/kvm/%s/cons"
  server = "on"
  wait = "off"
  logfile = "/dev/fd/1"
  logappend = "on"

[device]
  driver = "virtconsole"
  chardev = "charserial0"
  name = "org.lfedge.eve.console.0"



[device "pci.2"]
  driver = "pcie-root-port"
  port = "12"
  chassis = "2"
  bus = "pcie.0"
  addr = "0x2"

[device "usb"]
  driver = "qemu-xhci"
  p2 = "15"
  p3 = "15"
  bus = "pci.2"
  addr = "0x0"

[device "input0"]
  driver = "usb-tablet"
  bus = "usb.0"
  port = "1"


[device "pci.4"]
  driver = "pcie-root-port"
  port = "14"
  chassis = "4"
  bus = "pcie.0"
  addr = "0x4"

[drive "drive-virtio-disk0"]
  file = "/foo/bar.qcow2"
  format = "qcow2"
  aio = "io_uring"
  cache = "writeback"
  if = "none"

[device "virtio-disk0"]
  driver = "virtio-blk-pci"
  scsi = "off"
  bus = "pci.4"
  addr = "0x0"
  drive = "drive-virtio-disk0"


[fsdev "fsdev1"]
  fsdriver = "local"
  security_model = "none"
  multidevs = "remap"
  path = "/foo/container"

[device "fs1"]
  driver = "virtio-9p-pci"
  fsdev = "fsdev1"
  mount_tag = "share_dir"
  addr = "0x5"


[device "pci.6"]
  driver = "pcie-root-port"
  port = "16"
  chassis = "6"
  bus = "pcie.0"
  addr = "0x6"

[drive "drive-virtio-disk2"]
  file = "/foo/bar.raw"
  format = "raw"
  aio = "io_uring"
  cache = "writeback"
  if = "none"

[device "virtio-disk2"]
  driver = "virtio-blk-pci"
  scsi = "off"
  bus = "pci.6"
  addr = "0x0"
  drive = "drive-virtio-disk2"


[drive "drive-sata0-3"]
  file = "/foo/cd.iso"
  format = "raw"
  if = "none"
  media = "cdrom"
  readonly = "on"

[device "sata0-0"]
  drive = "drive-sata0-3"
  driver = "ide-cd"
  bus = "ide.0"

[device "pci.7"]
  driver = "pcie-root-port"
  port = "17"
  chassis = "7"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x7"

[netdev "hostnet0"]
  type = "tap"
  ifname = "nbu1x1"
  br = "bn0"
  script = "/etc/xen/scripts/qemu-ifup"
  downscript = "no"
  vhost = "on"

[device "net0"]
  driver = "virtio-net-pci"
  netdev = "hostnet0"
  mac = "6a:00:03:61:a6:90"
  bus = "pci.7"
  addr = "0x0"

[device "pci.8"]
  driver = "pcie-root-port"
  port = "18"
  chassis = "8"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x8"

[netdev "hostnet1"]
  type = "tap"
  ifname = "nbu1x2"
  br = "bn0"
  script = "/etc/xen/scripts/qemu-ifup"
  downscript = "no"
  vhost = "on"

[device "net1"]
  driver = "virtio-net-pci"
  netdev = "hostnet1"
  mac = "6a:00:03:61:a6:91"
  bus = "pci.8"
  addr = "0x0"

[chardev "charserial-usr0"]
  backend = "serial"
  path = "/dev/ttyS0"

[device "serial-usr0"]
  driver = "isa-serial"
  chardev = "charserial-usr0"

[device "eve-vsock0"]
  driver = "vhost-vsock-pci"
  disable-legacy = "on"
  guest-cid = "3"
`, DefaultUUID, DefaultDomainName, DefaultDomainName, DefaultDomainName)
		if string(result) != expected {
			t.Errorf("got an unexpected resulting config %s", string(result))
		}
	})

	config.VirtualizationMode = types.HVM
	config.BootLoader = "/usr/lib/xen/boot/ovmf.bin"
	t.Run("arm64", func(t *testing.T) {
		conf.Seek(0, 0)
		if err := kvmArm.CreateDomConfig(DefaultDomainName, config, types.DomainStatus{},
			disks, &aa, nil, swtpmCtrlSock, conf); err != nil {
			t.Errorf("CreateDomConfig failed %v", err)
		}
		defer os.Truncate(conf.Name(), 0)

		result, err := os.ReadFile(conf.Name())
		if err != nil {
			t.Errorf("reading conf file failed %v", err)
		}

		result = setStaticVsockCid(result)
		expected := fmt.Sprintf(`# This file is automatically generated by domainmgr
[msg]
  timestamp = "on"

[machine]
  type = "virt"
  dump-guest-core = "off"
  accel = "kvm:tcg"
  gic-version = "host"
  firmware = "/usr/lib/xen/boot/ovmf.bin"
  kernel = "/boot/kernel"
  initrd = "/boot/ramdisk"
  append = "init=/bin/sh"


[overcommit]
  mem-lock = "off"

[chardev "charmonitor"]
  backend = "socket"
  path = "/run/hypervisor/kvm/%s/qmp"
  server = "on"
  wait = "off"

[mon "monitor"]
  chardev = "charmonitor"
  mode = "control"

[chardev "charlistener"]
  backend = "socket"
  path = "/run/hypervisor/kvm/%s/listener.qmp"
  server = "on"
  wait = "off"

[mon "listener"]
  chardev = "charlistener"
  mode = "control"

[memory]
  size = "10240"

[smp-opts]
  cpus = "2"
  sockets = "1"
  cores = "2"
  threads = "1"

[device]
  driver = "virtio-serial"
  addr = "3"

[chardev "charserial0"]
  backend = "socket"
  mux = "on"
  path = "/run/hypervisor/kvm/%s/cons"
  server = "on"
  wait = "off"
  logfile = "/dev/fd/1"
  logappend = "on"

[device]
  driver = "virtconsole"
  chardev = "charserial0"
  name = "org.lfedge.eve.console.0"



[device "pci.2"]
  driver = "pcie-root-port"
  port = "12"
  chassis = "2"
  bus = "pcie.0"
  addr = "0x2"

[device "usb"]
  driver = "qemu-xhci"
  p2 = "15"
  p3 = "15"
  bus = "pci.2"
  addr = "0x0"

[device "input0"]
  driver = "usb-kbd"
  bus = "usb.0"
  port = "1"

[device "input1"]
  driver = "usb-mouse"
  bus = "usb.0"
  port = "2"


[device "pci.4"]
  driver = "pcie-root-port"
  port = "14"
  chassis = "4"
  bus = "pcie.0"
  addr = "0x4"

[drive "drive-virtio-disk0"]
  file = "/foo/bar.qcow2"
  format = "qcow2"
  aio = "io_uring"
  cache = "writeback"
  if = "none"

[device "virtio-disk0"]
  driver = "virtio-blk-pci"
  scsi = "off"
  bus = "pci.4"
  addr = "0x0"
  drive = "drive-virtio-disk0"


[fsdev "fsdev1"]
  fsdriver = "local"
  security_model = "none"
  multidevs = "remap"
  path = "/foo/container"

[device "fs1"]
  driver = "virtio-9p-pci"
  fsdev = "fsdev1"
  mount_tag = "share_dir"
  addr = "0x5"


[device "pci.6"]
  driver = "pcie-root-port"
  port = "16"
  chassis = "6"
  bus = "pcie.0"
  addr = "0x6"

[drive "drive-virtio-disk2"]
  file = "/foo/bar.raw"
  format = "raw"
  aio = "io_uring"
  cache = "writeback"
  if = "none"

[device "virtio-disk2"]
  driver = "virtio-blk-pci"
  scsi = "off"
  bus = "pci.6"
  addr = "0x0"
  drive = "drive-virtio-disk2"


[drive "drive-sata0-3"]
  file = "/foo/cd.iso"
  format = "raw"
  if = "none"
  media = "cdrom"
  readonly = "on"

[device "sata0-0"]
  drive = "drive-sata0-3"
  driver = "usb-storage"


[device "pci.7"]
  driver = "pcie-root-port"
  port = "17"
  chassis = "7"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x7"

[netdev "hostnet0"]
  type = "tap"
  ifname = "nbu1x1"
  br = "bn0"
  script = "/etc/xen/scripts/qemu-ifup"
  downscript = "no"
  vhost = "on"

[device "net0"]
  driver = "virtio-net-pci"
  netdev = "hostnet0"
  mac = "6a:00:03:61:a6:90"
  bus = "pci.7"
  addr = "0x0"

[device "pci.8"]
  driver = "pcie-root-port"
  port = "18"
  chassis = "8"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x8"

[netdev "hostnet1"]
  type = "tap"
  ifname = "nbu1x2"
  br = "bn0"
  script = "/etc/xen/scripts/qemu-ifup"
  downscript = "no"
  vhost = "on"

[device "net1"]
  driver = "virtio-net-pci"
  netdev = "hostnet1"
  mac = "6a:00:03:61:a6:91"
  bus = "pci.8"
  addr = "0x0"

[chardev "charserial-usr0"]
  backend = "serial"
  path = "/dev/ttyS0"

[device "serial-usr0"]
  driver = "pci-serial"
  chardev = "charserial-usr0"

[device "eve-vsock0"]
  driver = "vhost-vsock-pci"
  disable-legacy = "on"
  guest-cid = "3"
`, DefaultDomainName, DefaultDomainName, DefaultDomainName)
		if string(result) != expected {
			t.Errorf("got an unexpected resulting config %s", string(result))
		}
	})
}

func TestCreateDomConfigAmd64(t *testing.T) {
	t.Parallel()

	conf, err := os.CreateTemp("/tmp", "config")
	if err != nil {
		t.Errorf("Can't create config file for a domain %v", err)
	}
	defer os.Remove(conf.Name())

	diskConfigs, diskStatuses := qemuDisks()
	config, aa := domainConfigAndAssignableAdapters(diskConfigs)
	if err := kvmIntel.CreateDomConfig(DefaultDomainName, config, types.DomainStatus{},
		diskStatuses, &aa, nil, swtpmCtrlSock, conf); err != nil {
		t.Errorf("CreateDomConfig failed %v", err)
	}
	defer os.Truncate(conf.Name(), 0)

	result, err := os.ReadFile(conf.Name())
	if err != nil {
		t.Errorf("reading conf file failed %v", err)
	}

	result = setStaticVsockCid(result)
	if string(result) != domConfigAmd64() {
		t.Errorf("got an unexpected resulting config %s", string(result))
	}
}

func TestCreateDomConfigAmd64Legacy(t *testing.T) {
	t.Parallel()

	conf, err := os.CreateTemp("/tmp", "config")
	if err != nil {
		t.Errorf("Can't create config file for a domain %v", err)
	}
	defer os.Remove(conf.Name())
	diskCondigsLegacy, diskStatusesLegacy := qemuDisksLegacy()
	config, aa := domainConfigAndAssignableAdapters(diskCondigsLegacy)
	config.VirtualizationMode = types.LEGACY
	if err := kvmIntel.CreateDomConfig(DefaultDomainName, config, types.DomainStatus{},
		diskStatusesLegacy, &aa, nil, swtpmCtrlSock, conf); err != nil {
		t.Errorf("CreateDomConfig failed %v", err)
	}
	defer os.Truncate(conf.Name(), 0)

	result, err := os.ReadFile(conf.Name())
	if err != nil {
		t.Errorf("reading conf file failed %v", err)
	}

	result = setStaticVsockCid(result)
	if string(result) != domConfigAmd64Legacy() {
		t.Errorf("got an unexpected resulting config %s", string(result))
	}
}
func TestCreateDomConfigAmd64Fml(t *testing.T) {
	t.Parallel()

	conf, err := os.CreateTemp("/tmp", "config")
	if err != nil {
		t.Errorf("Can't create config file for a domain %v", err)
	}
	defer os.Remove(conf.Name())
	diskConfigs, diskStatuses := qemuDisks()
	config, aa := domainConfigAndAssignableAdapters(diskConfigs)
	config.VirtualizationMode = types.FML
	config.BootLoader = "/usr/lib/xen/boot/OVMF_CODE.fd"
	addNonExistingAdapter(&config, &aa)
	if err := kvmIntel.CreateDomConfig(DefaultDomainName, config, types.DomainStatus{},
		diskStatuses, &aa, nil, swtpmCtrlSock, conf); err != nil {
		t.Errorf("CreateDomConfig failed %v", err)
	}
	aa.IoBundleList = aa.IoBundleList[:len(aa.IoBundleList)-1]
	config.IoAdapterList = config.IoAdapterList[:len(config.IoAdapterList)-1]
	defer os.Truncate(conf.Name(), 0)

	result, err := os.ReadFile(conf.Name())
	if err != nil {
		t.Errorf("reading conf file failed %v", err)
	}

	result = setStaticVsockCid(result)
	if string(result) != domConfigAmd64FML() {
		t.Errorf("got an unexpected resulting config %s", cmp.Diff(string(result), domConfigAmd64FML()))
	}
}

func TestCreateDomConfigAmd64FmlWithBootOrder(t *testing.T) {
	t.Parallel()

	conf, err := os.CreateTemp("/tmp", "config")
	if err != nil {
		t.Errorf("Can't create config file for a domain %v", err)
	}
	defer os.Remove(conf.Name())

	diskConfigs, diskStatuses := qemuDisks()
	config, aa := domainConfigAndAssignableAdapters(diskConfigs)
	config.VirtualizationMode = types.FML
	config.BootLoader = "/usr/lib/xen/boot/OVMF_CODE.fd"
	config.BootOrder = zcommon.BootOrder_BOOT_ORDER_USB // Test USB boot order prioritization

	if err := kvmIntel.CreateDomConfig(DefaultDomainName, config, types.DomainStatus{},
		diskStatuses, &aa, nil, swtpmCtrlSock, conf); err != nil {
		t.Errorf("CreateDomConfig failed %v", err)
	}
	defer os.Truncate(conf.Name(), 0)

	result, err := os.ReadFile(conf.Name())
	if err != nil {
		t.Errorf("reading conf file failed %v", err)
	}

	// Verify that fw_cfg boot order section is present in the config
	if !bytes.Contains(result, []byte(`[fw_cfg]`)) {
		t.Error("expected [fw_cfg] section for boot order, but not found")
	}
	if !bytes.Contains(result, []byte(`name = "opt/eve.bootorder"`)) {
		t.Error("expected opt/eve.bootorder fw_cfg name, but not found")
	}
	if !bytes.Contains(result, []byte(`string = "usb"`)) {
		t.Error("expected boot order value 'usb', but not found")
	}
}

func TestCreateDomConfigAmd64FmlWithNoUsbBootOrder(t *testing.T) {
	t.Parallel()

	conf, err := os.CreateTemp("/tmp", "config")
	if err != nil {
		t.Errorf("Can't create config file for a domain %v", err)
	}
	defer os.Remove(conf.Name())

	diskConfigs, diskStatuses := qemuDisks()
	config, aa := domainConfigAndAssignableAdapters(diskConfigs)
	config.VirtualizationMode = types.FML
	config.BootLoader = "/usr/lib/xen/boot/OVMF_CODE.fd"
	config.BootOrder = zcommon.BootOrder_BOOT_ORDER_NOUSB // Test USB boot order deprioritization

	if err := kvmIntel.CreateDomConfig(DefaultDomainName, config, types.DomainStatus{},
		diskStatuses, &aa, nil, swtpmCtrlSock, conf); err != nil {
		t.Errorf("CreateDomConfig failed %v", err)
	}
	defer os.Truncate(conf.Name(), 0)

	result, err := os.ReadFile(conf.Name())
	if err != nil {
		t.Errorf("reading conf file failed %v", err)
	}

	// Verify that fw_cfg boot order section is present with nousb value
	if !bytes.Contains(result, []byte(`[fw_cfg]`)) {
		t.Error("expected [fw_cfg] section for boot order, but not found")
	}
	if !bytes.Contains(result, []byte(`string = "nousb"`)) {
		t.Error("expected boot order value 'nousb', but not found")
	}
}

func TestCreateDomConfigAmd64FmlWithoutBootOrder(t *testing.T) {
	t.Parallel()

	conf, err := os.CreateTemp("/tmp", "config")
	if err != nil {
		t.Errorf("Can't create config file for a domain %v", err)
	}
	defer os.Remove(conf.Name())

	diskConfigs, diskStatuses := qemuDisks()
	config, aa := domainConfigAndAssignableAdapters(diskConfigs)
	config.VirtualizationMode = types.FML
	config.BootLoader = "/usr/lib/xen/boot/OVMF_CODE.fd"
	// config.BootOrder is empty (default) - no boot order modification

	if err := kvmIntel.CreateDomConfig(DefaultDomainName, config, types.DomainStatus{},
		diskStatuses, &aa, nil, swtpmCtrlSock, conf); err != nil {
		t.Errorf("CreateDomConfig failed %v", err)
	}
	defer os.Truncate(conf.Name(), 0)

	result, err := os.ReadFile(conf.Name())
	if err != nil {
		t.Errorf("reading conf file failed %v", err)
	}

	// Verify that fw_cfg boot order section is NOT present when boot order is empty
	if bytes.Contains(result, []byte(`name = "opt/eve.bootorder"`)) {
		t.Error("unexpected opt/eve.bootorder fw_cfg - should not be present when boot order is empty")
	}
}

func TestCreateDomConfigArm64BootOrderIgnored(t *testing.T) {
	t.Parallel()

	conf, err := os.CreateTemp("/tmp", "config")
	if err != nil {
		t.Errorf("Can't create config file for a domain %v", err)
	}
	defer os.Remove(conf.Name())

	diskConfigs, diskStatuses := qemuDisks()
	config, aa := domainConfigAndAssignableAdapters(diskConfigs)
	config.VirtualizationMode = types.FML
	config.BootLoader = "/usr/lib/xen/boot/OVMF_CODE.fd"
	config.BootOrder = zcommon.BootOrder_BOOT_ORDER_USB // Set boot order

	// Use ARM context (virt machine) - boot order should be ignored
	if err := kvmArm.CreateDomConfig(DefaultDomainName, config, types.DomainStatus{},
		diskStatuses, &aa, nil, swtpmCtrlSock, conf); err != nil {
		t.Errorf("CreateDomConfig failed %v", err)
	}
	defer os.Truncate(conf.Name(), 0)

	result, err := os.ReadFile(conf.Name())
	if err != nil {
		t.Errorf("reading conf file failed %v", err)
	}

	// ARM (virt machine) uses an unpatched OVMF without EveBootOrderLib, so fw_cfg boot order should NOT be present
	if bytes.Contains(result, []byte(`name = "opt/eve.bootorder"`)) {
		t.Error("unexpected opt/eve.bootorder fw_cfg on ARM - EveBootOrderLib is not available on virt machine")
	}
}

func TestCreateDomConfigArm64(t *testing.T) {
	t.Parallel()

	conf, err := os.CreateTemp("/tmp", "config")
	if err != nil {
		t.Errorf("Can't create config file for a domain %v", err)
	}
	defer os.Remove(conf.Name())

	diskConfigs, diskStatuses := qemuDisks()
	config, aa := domainConfigAndAssignableAdapters(diskConfigs)
	config.VirtualizationMode = types.HVM
	config.BootLoader = "/usr/lib/xen/boot/ovmf.bin"
	if err := kvmArm.CreateDomConfig(DefaultDomainName, config, types.DomainStatus{},
		diskStatuses, &aa, nil, swtpmCtrlSock, conf); err != nil {
		t.Errorf("CreateDomConfig failed %v", err)
	}
	defer os.Truncate(conf.Name(), 0)

	result, err := os.ReadFile(conf.Name())
	if err != nil {
		t.Errorf("reading conf file failed %v", err)
	}

	result = setStaticVsockCid(result)
	if string(result) != domConfigArm64() {
		t.Errorf("got an unexpected resulting config %s", string(result))
	}
}

func addNonExistingAdapter(config *types.DomainConfig, aa *types.AssignableAdapters) {
	config.IoAdapterList = append(config.IoAdapterList, types.IoAdapter{
		Type: types.IoNetEth,
		Name: "eth1",
	})

	aa.IoBundleList = append(aa.IoBundleList, types.IoBundle{
		Type:            types.IoNetEth,
		AssignmentGroup: "eth1-1",
		Phylabel:        "eth1",
		Ifname:          "eth1",
		PciLong:         "0000:f4:00.0",
		UsedByUUID:      config.UUIDandVersion.UUID,
	})
}

func qemuDisks() ([]types.DiskConfig, []types.DiskStatus) {
	dc := []types.DiskConfig{
		{Format: zconfig.Format_QCOW2, FileLocation: "/foo/bar.qcow2"},
		{Format: zconfig.Format_CONTAINER, FileLocation: "/foo/container"},
		{Format: zconfig.Format_RAW, FileLocation: "/foo/bar.raw"},
		{Format: zconfig.Format_RAW, FileLocation: "/foo/cd.iso"},
		{Format: zconfig.Format_CONTAINER, FileLocation: "/foo/volume"},
		{Format: zconfig.Format_RAW, WWN: "naa.000000000000000a"},
	}
	ds := []types.DiskStatus{
		{Format: zconfig.Format_QCOW2, FileLocation: "/foo/bar.qcow2", Devtype: "hdd"},
		{Format: zconfig.Format_CONTAINER, FileLocation: "/foo/container", Devtype: "9P"},
		{Format: zconfig.Format_RAW, FileLocation: "/foo/bar.raw", Devtype: "hdd"},
		{Format: zconfig.Format_RAW, FileLocation: "/foo/cd.iso", Devtype: "cdrom"},
		{Format: zconfig.Format_CONTAINER, FileLocation: "/foo/volume", Devtype: ""},
		{Format: zconfig.Format_RAW, WWN: "naa.000000000000000a", Devtype: "hdd"},
	}
	return dc, ds
}

func domainConfigAndAssignableAdapters(dcl []types.DiskConfig) (types.DomainConfig, types.AssignableAdapters) {
	id, err := uuid.NewV4()
	if err != nil {
		panic(fmt.Errorf("NewV4 failed: %v", err))
	}

	config := types.DomainConfig{
		UUIDandVersion: types.UUIDandVersion{UUID: id, Version: "1.0"},
		VmConfig: types.VmConfig{
			Kernel:     "/boot/kernel",
			Ramdisk:    "/boot/ramdisk",
			ExtraArgs:  "init=/bin/sh",
			Memory:     1024 * 1024 * 10,
			VCpus:      2,
			EnableVnc:  true,
			VncDisplay: 5,
			VncPasswd:  "rosebud",
		},
		GPUConfig:      "legacy",
		DiskConfigList: dcl,
		VifList: []types.VifConfig{
			{Bridge: "bn0", Mac: net.HardwareAddr{0x6a, 0x00, 0x03, 0x61, 0xa6, 0x90}, Vif: "nbu1x1"},
			{Bridge: "bn0", Mac: net.HardwareAddr{0x6a, 0x00, 0x03, 0x61, 0xa6, 0x91}, Vif: "nbu1x2"},
		},
		IoAdapterList: []types.IoAdapter{
			{Type: types.IoNetEth, Name: "eth0"},
			{Type: types.IoCom, Name: "COM1"},
			{Type: types.IoUSBDevice, Name: "USB1"},
		},
	}

	aa := types.AssignableAdapters{
		Initialized: true,
		IoBundleList: []types.IoBundle{
			{
				Type:            types.IoNetEth,
				AssignmentGroup: "eth0-1",
				Phylabel:        "eth0",
				Ifname:          "eth0",
				PciLong:         "0000:f3:00.0",
				UsedByUUID:      config.UUIDandVersion.UUID,
			},
			{
				Type:            types.IoCom,
				AssignmentGroup: "COM1",
				Phylabel:        "COM1",
				Ifname:          "COM1",
				Serial:          "/dev/ttyS0",
				UsedByUUID:      config.UUIDandVersion.UUID,
			},
			{
				Type:            types.IoUSBDevice,
				AssignmentGroup: "USB1",
				Phylabel:        "USB1:1",
				UsbAddr:         "1:1",
				UsedByUUID:      config.UUIDandVersion.UUID,
			},
		},
	}
	return config, aa
}

func qemuDisksLegacy() ([]types.DiskConfig, []types.DiskStatus) {
	dc := []types.DiskConfig{
		{Format: zconfig.Format_QCOW2, FileLocation: "/foo/bar.qcow2"},
		{Format: zconfig.Format_CONTAINER, FileLocation: "/foo/container"},
		{Format: zconfig.Format_RAW, FileLocation: "/foo/bar.raw"},
		{Format: zconfig.Format_RAW, FileLocation: "/foo/cd.iso"},
		{Format: zconfig.Format_CONTAINER, FileLocation: "/foo/volume"},
		{Format: zconfig.Format_RAW, WWN: "naa.000000000000000a"},
	}
	ds := []types.DiskStatus{
		{Format: zconfig.Format_QCOW2, FileLocation: "/foo/bar.qcow2", Devtype: "legacy"},
		{Format: zconfig.Format_CONTAINER, FileLocation: "/foo/container", Devtype: "9P"},
		{Format: zconfig.Format_RAW, FileLocation: "/foo/bar.raw", Devtype: "legacy"},
		{Format: zconfig.Format_RAW, FileLocation: "/foo/cd.iso", Devtype: "cdrom"},
		{Format: zconfig.Format_CONTAINER, FileLocation: "/foo/volume", Devtype: ""},
		{Format: zconfig.Format_RAW, WWN: "naa.000000000000000a", Devtype: "legacy"},
	}
	return dc, ds
}

func domConfigArm64() string {
	return fmt.Sprintf(`# This file is automatically generated by domainmgr
[msg]
  timestamp = "on"

[machine]
  type = "virt"
  dump-guest-core = "off"
  accel = "kvm:tcg"
  gic-version = "host"
  firmware = "/usr/lib/xen/boot/ovmf.bin"
  kernel = "/boot/kernel"
  initrd = "/boot/ramdisk"
  append = "init=/bin/sh"


[overcommit]
  mem-lock = "off"

[chardev "charmonitor"]
  backend = "socket"
  path = "/run/hypervisor/kvm/%s/qmp"
  server = "on"
  wait = "off"

[mon "monitor"]
  chardev = "charmonitor"
  mode = "control"

[chardev "charlistener"]
  backend = "socket"
  path = "/run/hypervisor/kvm/%s/listener.qmp"
  server = "on"
  wait = "off"

[mon "listener"]
  chardev = "charlistener"
  mode = "control"

[memory]
  size = "10240"

[smp-opts]
  cpus = "2"
  sockets = "1"
  cores = "2"
  threads = "1"

[device]
  driver = "virtio-serial"
  addr = "3"

[chardev "charserial0"]
  backend = "socket"
  mux = "on"
  path = "/run/hypervisor/kvm/%s/cons"
  server = "on"
  wait = "off"
  logfile = "/dev/fd/1"
  logappend = "on"

[device]
  driver = "virtconsole"
  chardev = "charserial0"
  name = "org.lfedge.eve.console.0"



[vnc "default"]
  vnc = "0.0.0.0:5"
  to = "99"
  password = "on"
[device "video0"]
  driver = "virtio-gpu-pci"
[device "pci.2"]
  driver = "pcie-root-port"
  port = "12"
  chassis = "2"
  bus = "pcie.0"
  addr = "0x2"

[device "usb"]
  driver = "qemu-xhci"
  p2 = "15"
  p3 = "15"
  bus = "pci.2"
  addr = "0x0"

[device "input0"]
  driver = "usb-kbd"
  bus = "usb.0"
  port = "1"

[device "input1"]
  driver = "usb-mouse"
  bus = "usb.0"
  port = "2"


[device "pci.4"]
  driver = "pcie-root-port"
  port = "14"
  chassis = "4"
  bus = "pcie.0"
  addr = "0x4"

[drive "drive-virtio-disk0"]
  file = "/foo/bar.qcow2"
  format = "qcow2"
  aio = "io_uring"
  cache = "writeback"
  if = "none"

[device "virtio-disk0"]
  driver = "virtio-blk-pci"
  scsi = "off"
  bus = "pci.4"
  addr = "0x0"
  drive = "drive-virtio-disk0"


[fsdev "fsdev1"]
  fsdriver = "local"
  security_model = "none"
  multidevs = "remap"
  path = "/foo/container"

[device "fs1"]
  driver = "virtio-9p-pci"
  fsdev = "fsdev1"
  mount_tag = "share_dir"
  addr = "0x5"


[device "pci.6"]
  driver = "pcie-root-port"
  port = "16"
  chassis = "6"
  bus = "pcie.0"
  addr = "0x6"

[drive "drive-virtio-disk2"]
  file = "/foo/bar.raw"
  format = "raw"
  aio = "io_uring"
  cache = "writeback"
  if = "none"

[device "virtio-disk2"]
  driver = "virtio-blk-pci"
  scsi = "off"
  bus = "pci.6"
  addr = "0x0"
  drive = "drive-virtio-disk2"


[drive "drive-sata0-3"]
  file = "/foo/cd.iso"
  format = "raw"
  if = "none"
  media = "cdrom"
  readonly = "on"

[device "sata0-0"]
  drive = "drive-sata0-3"
  driver = "usb-storage"



[device "pci.7"]
  driver = "pcie-root-port"
  port = "17"
  chassis = "7"
  bus = "pcie.0"
  addr = "0x7"

[device "vhost-disk4"]
  driver = "vhost-scsi-pci"
  max_sectors = "16384"
  wwpn = "naa.000000000000000a"
  bus = "pci.7"
  addr = "0x0"
  num_queues = "2"

[device "pci.8"]
  driver = "pcie-root-port"
  port = "18"
  chassis = "8"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x8"

[netdev "hostnet0"]
  type = "tap"
  ifname = "nbu1x1"
  br = "bn0"
  script = "/etc/xen/scripts/qemu-ifup"
  downscript = "no"
  vhost = "on"

[device "net0"]
  driver = "virtio-net-pci"
  netdev = "hostnet0"
  mac = "6a:00:03:61:a6:90"
  bus = "pci.8"
  addr = "0x0"

[device "pci.9"]
  driver = "pcie-root-port"
  port = "19"
  chassis = "9"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x9"

[netdev "hostnet1"]
  type = "tap"
  ifname = "nbu1x2"
  br = "bn0"
  script = "/etc/xen/scripts/qemu-ifup"
  downscript = "no"
  vhost = "on"

[device "net1"]
  driver = "virtio-net-pci"
  netdev = "hostnet1"
  mac = "6a:00:03:61:a6:91"
  bus = "pci.9"
  addr = "0x0"

[device "pci.10"]
  driver = "pcie-root-port"
  port = "110"
  chassis = "10"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0xa"

[device]
  driver = "vfio-pci"
  host = "f3:00.0"
  bus = "pci.10"
  addr = "0x0"

[chardev "charserial-usr0"]
  backend = "serial"
  path = "/dev/ttyS0"

[device "serial-usr0"]
  driver = "pci-serial"
  chardev = "charserial-usr0"

[device "eve-vsock0"]
  driver = "vhost-vsock-pci"
  disable-legacy = "on"
  guest-cid = "3"
`, DefaultDomainName, DefaultDomainName, DefaultDomainName)
}

func domConfigAmd64FML() string {
	return fmt.Sprintf(`# This file is automatically generated by domainmgr
[msg]
  timestamp = "on"

[machine]
  type = "pc-q35-3.1"
  dump-guest-core = "off"
  accel = "kvm"
  vmport = "off"
  kernel-irqchip = "on"
  kernel = "/boot/kernel"
  initrd = "/boot/ramdisk"
  append = "init=/bin/sh"

[global]
  driver = "kvm-pit"
  property = "lost_tick_policy"
  value = "delay"

[global]
  driver = "ICH9-LPC"
  property = "disable_s3"
  value = "1"

[global]
  driver = "ICH9-LPC"
  property = "disable_s4"
  value = "1"

[rtc]
  base = "localtime"
  driftfix = "slew"

[device]
  driver = "intel-iommu"
  caching-mode = "on"

[drive "drive-ovmf-code"]
  if = "pflash"
  format = "raw"
  readonly = "on"
  unit = "0"
  file = "/usr/lib/xen/boot/OVMF_CODE.fd"

[drive "drive-ovmf-vars"]
  if = "pflash"
  format = "raw"
  unit = "1"
  file = "/persist/vault/ovmf/%s_OVMF_VARS.fd"

[overcommit]
  mem-lock = "off"

[chardev "charmonitor"]
  backend = "socket"
  path = "/run/hypervisor/kvm/%s/qmp"
  server = "on"
  wait = "off"

[mon "monitor"]
  chardev = "charmonitor"
  mode = "control"

[chardev "charlistener"]
  backend = "socket"
  path = "/run/hypervisor/kvm/%s/listener.qmp"
  server = "on"
  wait = "off"

[mon "listener"]
  chardev = "charlistener"
  mode = "control"

[memory]
  size = "10240"

[smp-opts]
  cpus = "2"
  sockets = "1"
  cores = "2"
  threads = "1"

[device]
  driver = "virtio-serial"
  addr = "3"

[chardev "charserial0"]
  backend = "socket"
  mux = "on"
  path = "/run/hypervisor/kvm/%s/cons"
  server = "on"
  wait = "off"
  logfile = "/dev/fd/1"
  logappend = "on"

[device]
  driver = "virtconsole"
  chardev = "charserial0"
  name = "org.lfedge.eve.console.0"



[vnc "default"]
  vnc = "0.0.0.0:5"
  to = "99"
  password = "on"
[device "video0"]
  driver = "virtio-vga"
  bus = "pcie.0"
  addr = "0x1"
[device "pci.2"]
  driver = "pcie-root-port"
  port = "12"
  chassis = "2"
  bus = "pcie.0"
  addr = "0x2"

[device "usb"]
  driver = "qemu-xhci"
  p2 = "15"
  p3 = "15"
  bus = "pci.2"
  addr = "0x0"

[device "input0"]
  driver = "usb-tablet"
  bus = "usb.0"
  port = "1"


[device "pci.4"]
  driver = "pcie-root-port"
  port = "14"
  chassis = "4"
  bus = "pcie.0"
  addr = "0x4"

[drive "drive-virtio-disk0"]
  file = "/foo/bar.qcow2"
  format = "qcow2"
  aio = "io_uring"
  cache = "writeback"
  if = "none"

[device "virtio-disk0"]
  driver = "virtio-blk-pci"
  scsi = "off"
  bus = "pci.4"
  addr = "0x0"
  drive = "drive-virtio-disk0"


[fsdev "fsdev1"]
  fsdriver = "local"
  security_model = "none"
  multidevs = "remap"
  path = "/foo/container"

[device "fs1"]
  driver = "virtio-9p-pci"
  fsdev = "fsdev1"
  mount_tag = "share_dir"
  addr = "0x5"


[device "pci.6"]
  driver = "pcie-root-port"
  port = "16"
  chassis = "6"
  bus = "pcie.0"
  addr = "0x6"

[drive "drive-virtio-disk2"]
  file = "/foo/bar.raw"
  format = "raw"
  aio = "io_uring"
  cache = "writeback"
  if = "none"

[device "virtio-disk2"]
  driver = "virtio-blk-pci"
  scsi = "off"
  bus = "pci.6"
  addr = "0x0"
  drive = "drive-virtio-disk2"


[drive "drive-sata0-3"]
  file = "/foo/cd.iso"
  format = "raw"
  if = "none"
  media = "cdrom"
  readonly = "on"

[device "sata0-0"]
  drive = "drive-sata0-3"
  driver = "ide-cd"
  bus = "ide.0"


[device "pci.7"]
  driver = "pcie-root-port"
  port = "17"
  chassis = "7"
  bus = "pcie.0"
  addr = "0x7"

[device "vhost-disk4"]
  driver = "vhost-scsi-pci"
  max_sectors = "16384"
  wwpn = "naa.000000000000000a"
  bus = "pci.7"
  addr = "0x0"
  num_queues = "2"

[device "pci.8"]
  driver = "pcie-root-port"
  port = "18"
  chassis = "8"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x8"

[netdev "hostnet0"]
  type = "tap"
  ifname = "nbu1x1"
  br = "bn0"
  script = "/etc/xen/scripts/qemu-ifup"
  downscript = "no"
  vhost = "on"

[device "net0"]
  driver = "virtio-net-pci"
  netdev = "hostnet0"
  mac = "6a:00:03:61:a6:90"
  bus = "pci.8"
  addr = "0x0"

[device "pci.9"]
  driver = "pcie-root-port"
  port = "19"
  chassis = "9"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x9"

[netdev "hostnet1"]
  type = "tap"
  ifname = "nbu1x2"
  br = "bn0"
  script = "/etc/xen/scripts/qemu-ifup"
  downscript = "no"
  vhost = "on"

[device "net1"]
  driver = "virtio-net-pci"
  netdev = "hostnet1"
  mac = "6a:00:03:61:a6:91"
  bus = "pci.9"
  addr = "0x0"

[device "pci.10"]
  driver = "pcie-root-port"
  port = "110"
  chassis = "10"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0xa"

[device]
  driver = "vfio-pci"
  host = "f3:00.0"
  bus = "pci.10"
  addr = "0x0"

[device "pci.11"]
  driver = "pcie-root-port"
  port = "111"
  chassis = "11"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0xb"

[device]
  driver = "vfio-pci"
  host = "f4:00.0"
  bus = "pci.11"
  addr = "0x0"

[chardev "charserial-usr0"]
  backend = "serial"
  path = "/dev/ttyS0"

[device "serial-usr0"]
  driver = "isa-serial"
  chardev = "charserial-usr0"

[device "eve-vsock0"]
  driver = "vhost-vsock-pci"
  disable-legacy = "on"
  guest-cid = "3"
`, DefaultUUID, DefaultDomainName, DefaultDomainName, DefaultDomainName)
}

func domConfigAmd64Legacy() string {
	return fmt.Sprintf(`# This file is automatically generated by domainmgr
[msg]
  timestamp = "on"

[machine]
  type = "pc-q35-3.1"
  dump-guest-core = "off"
  accel = "kvm"
  vmport = "off"
  kernel-irqchip = "on"
  kernel = "/boot/kernel"
  initrd = "/boot/ramdisk"
  append = "init=/bin/sh"

[global]
  driver = "kvm-pit"
  property = "lost_tick_policy"
  value = "delay"

[global]
  driver = "ICH9-LPC"
  property = "disable_s3"
  value = "1"

[global]
  driver = "ICH9-LPC"
  property = "disable_s4"
  value = "1"

[rtc]
  base = "localtime"
  driftfix = "slew"

[device]
  driver = "intel-iommu"
  caching-mode = "on"

[overcommit]
  mem-lock = "off"

[chardev "charmonitor"]
  backend = "socket"
  path = "/run/hypervisor/kvm/%s/qmp"
  server = "on"
  wait = "off"

[mon "monitor"]
  chardev = "charmonitor"
  mode = "control"

[chardev "charlistener"]
  backend = "socket"
  path = "/run/hypervisor/kvm/%s/listener.qmp"
  server = "on"
  wait = "off"

[mon "listener"]
  chardev = "charlistener"
  mode = "control"

[memory]
  size = "10240"

[smp-opts]
  cpus = "2"
  sockets = "1"
  cores = "2"
  threads = "1"

[device]
  driver = "virtio-serial"
  addr = "3"

[chardev "charserial0"]
  backend = "socket"
  mux = "on"
  path = "/run/hypervisor/kvm/%s/cons"
  server = "on"
  wait = "off"
  logfile = "/dev/fd/1"
  logappend = "on"

[device]
  driver = "virtconsole"
  chardev = "charserial0"
  name = "org.lfedge.eve.console.0"



[vnc "default"]
  vnc = "0.0.0.0:5"
  to = "99"
  password = "on"
[device "video0"]
  driver = "virtio-vga"
  bus = "pcie.0"
  addr = "0x1"
[device "pci.2"]
  driver = "pcie-root-port"
  port = "12"
  chassis = "2"
  bus = "pcie.0"
  addr = "0x2"

[device "usb"]
  driver = "qemu-xhci"
  p2 = "15"
  p3 = "15"
  bus = "pci.2"
  addr = "0x0"

[device "input0"]
  driver = "usb-tablet"
  bus = "usb.0"
  port = "1"


[device "pci.4"]
  driver = "pcie-root-port"
  port = "14"
  chassis = "4"
  bus = "pcie.0"
  addr = "0x4"

[drive "drive-virtio-disk0"]
  file = "/foo/bar.qcow2"
  format = "qcow2"
  aio = "io_uring"
  cache = "writeback"
  if = "none"

[device "ahci.4"]
  bus = "pci.4"
  driver = "ahci"

[device "ahci-disk0"]
  driver = "ide-hd"
  bus = "ahci.4.0"
  drive = "drive-virtio-disk0"


[fsdev "fsdev1"]
  fsdriver = "local"
  security_model = "none"
  multidevs = "remap"
  path = "/foo/container"

[device "fs1"]
  driver = "virtio-9p-pci"
  fsdev = "fsdev1"
  mount_tag = "share_dir"
  addr = "0x5"


[device "pci.6"]
  driver = "pcie-root-port"
  port = "16"
  chassis = "6"
  bus = "pcie.0"
  addr = "0x6"

[drive "drive-virtio-disk2"]
  file = "/foo/bar.raw"
  format = "raw"
  aio = "io_uring"
  cache = "writeback"
  if = "none"

[device "ahci.6"]
  bus = "pci.6"
  driver = "ahci"

[device "ahci-disk2"]
  driver = "ide-hd"
  bus = "ahci.6.0"
  drive = "drive-virtio-disk2"


[drive "drive-sata0-3"]
  file = "/foo/cd.iso"
  format = "raw"
  if = "none"
  media = "cdrom"
  readonly = "on"

[device "sata0-0"]
  drive = "drive-sata0-3"
  driver = "ide-cd"
  bus = "ide.0"


[device "pci.7"]
  driver = "pcie-root-port"
  port = "17"
  chassis = "7"
  bus = "pcie.0"
  addr = "0x7"

[device "vhost-disk4"]
  driver = "vhost-scsi-pci"
  max_sectors = "16384"
  wwpn = "naa.000000000000000a"
  bus = "pci.7"
  addr = "0x0"
  num_queues = "2"

[device "pci.8"]
  driver = "pcie-root-port"
  port = "18"
  chassis = "8"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x8"

[netdev "hostnet0"]
  type = "tap"
  ifname = "nbu1x1"
  br = "bn0"
  script = "/etc/xen/scripts/qemu-ifup"
  downscript = "no"

[device "net0"]
  driver = "e1000"
  netdev = "hostnet0"
  mac = "6a:00:03:61:a6:90"
  bus = "pci.8"
  addr = "0x0"

[device "pci.9"]
  driver = "pcie-root-port"
  port = "19"
  chassis = "9"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x9"

[netdev "hostnet1"]
  type = "tap"
  ifname = "nbu1x2"
  br = "bn0"
  script = "/etc/xen/scripts/qemu-ifup"
  downscript = "no"

[device "net1"]
  driver = "e1000"
  netdev = "hostnet1"
  mac = "6a:00:03:61:a6:91"
  bus = "pci.9"
  addr = "0x0"

[device "pci.10"]
  driver = "pcie-root-port"
  port = "110"
  chassis = "10"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0xa"

[device]
  driver = "vfio-pci"
  host = "f3:00.0"
  bus = "pci.10"
  addr = "0x0"

[chardev "charserial-usr0"]
  backend = "serial"
  path = "/dev/ttyS0"

[device "serial-usr0"]
  driver = "isa-serial"
  chardev = "charserial-usr0"

[device "eve-vsock0"]
  driver = "vhost-vsock-pci"
  disable-legacy = "on"
  guest-cid = "3"
`, DefaultDomainName, DefaultDomainName, DefaultDomainName)
}

func domConfigAmd64() string {
	return fmt.Sprintf(`# This file is automatically generated by domainmgr
[msg]
  timestamp = "on"

[machine]
  type = "pc-q35-3.1"
  dump-guest-core = "off"
  accel = "kvm"
  vmport = "off"
  kernel-irqchip = "on"
  kernel = "/boot/kernel"
  initrd = "/boot/ramdisk"
  append = "init=/bin/sh"

[global]
  driver = "kvm-pit"
  property = "lost_tick_policy"
  value = "delay"

[global]
  driver = "ICH9-LPC"
  property = "disable_s3"
  value = "1"

[global]
  driver = "ICH9-LPC"
  property = "disable_s4"
  value = "1"

[rtc]
  base = "localtime"
  driftfix = "slew"

[device]
  driver = "intel-iommu"
  caching-mode = "on"

[overcommit]
  mem-lock = "off"

[chardev "charmonitor"]
  backend = "socket"
  path = "/run/hypervisor/kvm/%s/qmp"
  server = "on"
  wait = "off"

[mon "monitor"]
  chardev = "charmonitor"
  mode = "control"

[chardev "charlistener"]
  backend = "socket"
  path = "/run/hypervisor/kvm/%s/listener.qmp"
  server = "on"
  wait = "off"

[mon "listener"]
  chardev = "charlistener"
  mode = "control"

[memory]
  size = "10240"

[smp-opts]
  cpus = "2"
  sockets = "1"
  cores = "2"
  threads = "1"

[device]
  driver = "virtio-serial"
  addr = "3"

[chardev "charserial0"]
  backend = "socket"
  mux = "on"
  path = "/run/hypervisor/kvm/%s/cons"
  server = "on"
  wait = "off"
  logfile = "/dev/fd/1"
  logappend = "on"

[device]
  driver = "virtconsole"
  chardev = "charserial0"
  name = "org.lfedge.eve.console.0"



[vnc "default"]
  vnc = "0.0.0.0:5"
  to = "99"
  password = "on"
[device "video0"]
  driver = "virtio-vga"
  bus = "pcie.0"
  addr = "0x1"
[device "pci.2"]
  driver = "pcie-root-port"
  port = "12"
  chassis = "2"
  bus = "pcie.0"
  addr = "0x2"

[device "usb"]
  driver = "qemu-xhci"
  p2 = "15"
  p3 = "15"
  bus = "pci.2"
  addr = "0x0"

[device "input0"]
  driver = "usb-tablet"
  bus = "usb.0"
  port = "1"


[device "pci.4"]
  driver = "pcie-root-port"
  port = "14"
  chassis = "4"
  bus = "pcie.0"
  addr = "0x4"

[drive "drive-virtio-disk0"]
  file = "/foo/bar.qcow2"
  format = "qcow2"
  aio = "io_uring"
  cache = "writeback"
  if = "none"

[device "virtio-disk0"]
  driver = "virtio-blk-pci"
  scsi = "off"
  bus = "pci.4"
  addr = "0x0"
  drive = "drive-virtio-disk0"


[fsdev "fsdev1"]
  fsdriver = "local"
  security_model = "none"
  multidevs = "remap"
  path = "/foo/container"

[device "fs1"]
  driver = "virtio-9p-pci"
  fsdev = "fsdev1"
  mount_tag = "share_dir"
  addr = "0x5"


[device "pci.6"]
  driver = "pcie-root-port"
  port = "16"
  chassis = "6"
  bus = "pcie.0"
  addr = "0x6"

[drive "drive-virtio-disk2"]
  file = "/foo/bar.raw"
  format = "raw"
  aio = "io_uring"
  cache = "writeback"
  if = "none"

[device "virtio-disk2"]
  driver = "virtio-blk-pci"
  scsi = "off"
  bus = "pci.6"
  addr = "0x0"
  drive = "drive-virtio-disk2"


[drive "drive-sata0-3"]
  file = "/foo/cd.iso"
  format = "raw"
  if = "none"
  media = "cdrom"
  readonly = "on"

[device "sata0-0"]
  drive = "drive-sata0-3"
  driver = "ide-cd"
  bus = "ide.0"


[device "pci.7"]
  driver = "pcie-root-port"
  port = "17"
  chassis = "7"
  bus = "pcie.0"
  addr = "0x7"

[device "vhost-disk4"]
  driver = "vhost-scsi-pci"
  max_sectors = "16384"
  wwpn = "naa.000000000000000a"
  bus = "pci.7"
  addr = "0x0"
  num_queues = "2"

[device "pci.8"]
  driver = "pcie-root-port"
  port = "18"
  chassis = "8"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x8"

[netdev "hostnet0"]
  type = "tap"
  ifname = "nbu1x1"
  br = "bn0"
  script = "/etc/xen/scripts/qemu-ifup"
  downscript = "no"
  vhost = "on"

[device "net0"]
  driver = "virtio-net-pci"
  netdev = "hostnet0"
  mac = "6a:00:03:61:a6:90"
  bus = "pci.8"
  addr = "0x0"

[device "pci.9"]
  driver = "pcie-root-port"
  port = "19"
  chassis = "9"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x9"

[netdev "hostnet1"]
  type = "tap"
  ifname = "nbu1x2"
  br = "bn0"
  script = "/etc/xen/scripts/qemu-ifup"
  downscript = "no"
  vhost = "on"

[device "net1"]
  driver = "virtio-net-pci"
  netdev = "hostnet1"
  mac = "6a:00:03:61:a6:91"
  bus = "pci.9"
  addr = "0x0"

[device "pci.10"]
  driver = "pcie-root-port"
  port = "110"
  chassis = "10"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0xa"

[device]
  driver = "vfio-pci"
  host = "f3:00.0"
  bus = "pci.10"
  addr = "0x0"

[chardev "charserial-usr0"]
  backend = "serial"
  path = "/dev/ttyS0"

[device "serial-usr0"]
  driver = "isa-serial"
  chardev = "charserial-usr0"

[device "eve-vsock0"]
  driver = "vhost-vsock-pci"
  disable-legacy = "on"
  guest-cid = "3"
`, DefaultDomainName, DefaultDomainName, DefaultDomainName)
}

func domConfigContainerVNC() string {
	return fmt.Sprintf(`# This file is automatically generated by domainmgr
[msg]
  timestamp = "on"

[machine]
  type = "pc-q35-3.1"
  dump-guest-core = "off"
  accel = "kvm"
  vmport = "off"
  kernel-irqchip = "on"
  kernel = "/boot/kernel"
  initrd = "/boot/ramdisk"
  append = "init=/bin/sh"

[global]
  driver = "kvm-pit"
  property = "lost_tick_policy"
  value = "delay"

[global]
  driver = "ICH9-LPC"
  property = "disable_s3"
  value = "1"

[global]
  driver = "ICH9-LPC"
  property = "disable_s4"
  value = "1"

[rtc]
  base = "localtime"
  driftfix = "slew"

[device]
  driver = "intel-iommu"
  caching-mode = "on"

[overcommit]
  mem-lock = "off"

[chardev "charmonitor"]
  backend = "socket"
  path = "/run/hypervisor/kvm/%s/qmp"
  server = "on"
  wait = "off"

[mon "monitor"]
  chardev = "charmonitor"
  mode = "control"

[chardev "charlistener"]
  backend = "socket"
  path = "/run/hypervisor/kvm/%s/listener.qmp"
  server = "on"
  wait = "off"

[mon "listener"]
  chardev = "charlistener"
  mode = "control"

[memory]
  size = "10240"

[smp-opts]
  cpus = "2"
  sockets = "1"
  cores = "2"
  threads = "1"

[device]
  driver = "virtio-serial"
  addr = "3"

[chardev "charserial0"]
  backend = "socket"
  mux = "on"
  path = "/run/hypervisor/kvm/%s/cons"
  server = "on"
  wait = "off"
  logfile = "/dev/fd/1"
  logappend = "on"

[device]
  driver = "virtconsole"
  chardev = "charserial0"
  name = "org.lfedge.eve.console.0"

[chardev "charserial1"]
  backend = "socket"
  path = "/run/hypervisor/kvm/%s/shim-cons"
  server = "on"
  wait = "off"

[chardev "charserial2"]
  backend = "vc"

[chardev "charhub0"]
  backend = "hub"
  chardevs.0 = "charserial1"
  chardevs.1 = "charserial2"
  logfile = "/dev/fd/1"
  logappend = "on"

[device]
  driver = "virtconsole"
  chardev = "charhub0"
  name = "org.lfedge.eve.console.shim"


[vnc "default"]
  vnc = "0.0.0.0:5"
  to = "99"
  password = "on"
[device "video0"]
  driver = "virtio-vga"
  bus = "pcie.0"
  addr = "0x1"
[device "pci.2"]
  driver = "pcie-root-port"
  port = "12"
  chassis = "2"
  bus = "pcie.0"
  addr = "0x2"

[device "usb"]
  driver = "qemu-xhci"
  p2 = "15"
  p3 = "15"
  bus = "pci.2"
  addr = "0x0"

[device "input0"]
  driver = "usb-tablet"
  bus = "usb.0"
  port = "1"


[fsdev "fsdev0"]
  fsdriver = "local"
  security_model = "none"
  multidevs = "remap"
  path = "/foo/container"

[device "fs0"]
  driver = "virtio-9p-pci"
  fsdev = "fsdev0"
  mount_tag = "share_dir"
  addr = "0x4"


[device "pci.5"]
  driver = "pcie-root-port"
  port = "15"
  chassis = "5"
  bus = "pcie.0"
  addr = "0x5"

[drive "drive-virtio-disk1"]
  file = "/foo/bar.raw"
  format = "raw"
  aio = "io_uring"
  cache = "writeback"
  if = "none"

[device "virtio-disk1"]
  driver = "virtio-blk-pci"
  scsi = "off"
  bus = "pci.5"
  addr = "0x0"
  drive = "drive-virtio-disk1"


[drive "drive-sata0-2"]
  file = "/foo/cd.iso"
  format = "raw"
  if = "none"
  media = "cdrom"
  readonly = "on"

[device "sata0-0"]
  drive = "drive-sata0-2"
  driver = "ide-cd"
  bus = "ide.0"


[device "pci.6"]
  driver = "pcie-root-port"
  port = "16"
  chassis = "6"
  bus = "pcie.0"
  addr = "0x6"

[device "vhost-disk3"]
  driver = "vhost-scsi-pci"
  max_sectors = "16384"
  wwpn = "naa.000000000000000a"
  bus = "pci.6"
  addr = "0x0"
  num_queues = "2"

[device "pci.7"]
  driver = "pcie-root-port"
  port = "17"
  chassis = "7"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x7"

[netdev "hostnet0"]
  type = "tap"
  ifname = "nbu1x1"
  br = "bn0"
  script = "/etc/xen/scripts/qemu-ifup"
  downscript = "no"
  vhost = "on"

[device "net0"]
  driver = "virtio-net-pci"
  netdev = "hostnet0"
  mac = "6a:00:03:61:a6:90"
  bus = "pci.7"
  addr = "0x0"

[device "pci.8"]
  driver = "pcie-root-port"
  port = "18"
  chassis = "8"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x8"

[netdev "hostnet1"]
  type = "tap"
  ifname = "nbu1x2"
  br = "bn0"
  script = "/etc/xen/scripts/qemu-ifup"
  downscript = "no"
  vhost = "on"

[device "net1"]
  driver = "virtio-net-pci"
  netdev = "hostnet1"
  mac = "6a:00:03:61:a6:91"
  bus = "pci.8"
  addr = "0x0"

[device "pci.9"]
  driver = "pcie-root-port"
  port = "19"
  chassis = "9"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x9"

[device]
  driver = "vfio-pci"
  host = "f3:00.0"
  bus = "pci.9"
  addr = "0x0"

[chardev "charserial-usr0"]
  backend = "serial"
  path = "/dev/ttyS0"

[device "serial-usr0"]
  driver = "isa-serial"
  chardev = "charserial-usr0"

[device "eve-vsock0"]
  driver = "vhost-vsock-pci"
  disable-legacy = "on"
  guest-cid = "3"
`, DefaultDomainName, DefaultDomainName, DefaultDomainName, DefaultDomainName)
}

func TestCreateDom(t *testing.T) {
	if exec.Command("qemu-system-x86_64", "--version").Run() != nil {
		// skipping this test since we're clearly not in a presence of qemu
		return
	}
	id, err := uuid.NewV4()
	if err != nil {
		t.Errorf("NewV4 failed: %v", err)
	}
	config := types.DomainConfig{
		UUIDandVersion: types.UUIDandVersion{UUID: id, Version: "1.0"},
		VmConfig: types.VmConfig{
			Kernel:             "/boot/kernel",
			Ramdisk:            "/boot/ramdisk",
			ExtraArgs:          "init=/bin/sh",
			Memory:             1024 * 1024 * 10,
			VCpus:              2,
			VncDisplay:         5,
			VncPasswd:          "rosebud",
			VirtualizationMode: types.HVM,
		},
		GPUConfig: "legacy",
		VifList: []types.VifConfig{
			{Bridge: "bn0", Mac: net.HardwareAddr{0x6a, 0x00, 0x03, 0x61, 0xa6, 0x90}, Vif: "nbu1x1"},
			{Bridge: "bn0", Mac: net.HardwareAddr{0x6a, 0x00, 0x03, 0x61, 0xa6, 0x91}, Vif: "nbu1x2"},
		},
		IoAdapterList: []types.IoAdapter{
			{Type: types.IoNetEth, Name: "eth0"},
			{Type: types.IoCom, Name: "COM1"},
		},
	}
	os.RemoveAll(kvmStateDir)

	conf, err := os.CreateTemp("/tmp/", "config")
	if err != nil {
		t.Errorf("Can't create config file for a domain %v", err)
	} else {
		defer os.Remove(conf.Name())
	}
	os.WriteFile(conf.Name(), []byte(fmt.Sprintf(
		`# This file is automatically generated by domainmgr
[msg]
  timestamp = "on"

[machine]
  type = "pc-q35-3.1"
  vmport = "off"
  dump-guest-core = "off"

[global]
  driver = "ICH9-LPC"
  property = "disable_s3"
  value = "1"

[global]
  driver = "ICH9-LPC"
  property = "disable_s4"
  value = "1"

[overcommit]
  mem-lock = "off"

[rtc]
  base = "localtime"
  driftfix = "slew"

[chardev "charmonitor"]
  backend = "socket"
  path = "/run/hypervisor/kvm/%s/qmp"
  server = "on"
  wait = "off"

[chardev "charlistener"]
  backend = "socket"
  path = "/run/hypervisor/kvm/%s/listener.qmp"
  server = "on"
  wait = "off"

[mon "listener"]
  chardev = "charlistener"
  mode = "control"

[mon "monitor"]
  chardev = "charmonitor"
  mode = "control"

[memory]
  size = "1024"

[smp-opts]
  cpus = "2"
  sockets = "1"
  cores = "2"
  threads = "1"`, DefaultDomainName, DefaultDomainName)), 0777)

	if kvmIntel.ctrdClient == nil {
		t.Skipf("test must be run on a system with a functional containerd")
	}

	if _, err := kvmIntel.Task(testDom).Create("test", conf.Name(), &config); err != nil {
		t.Errorf("Create domain config failed %v", err)
	}

	state, err := os.Open(kvmStateDir + "/test")
	if err != nil {
		t.Errorf("can't open stat dir for test domain %v", err)
	}

	names, err := state.Readdirnames(0)
	if err != nil || len(names) != 3 {
		t.Errorf("can't read stat dir for test domain or got unexpected content %v", err)
	}

	for _, e := range names {
		if _, found := map[string]bool{"pid": true, "qmp": true, "cons": true}[e]; !found {
			t.Errorf("got an unexpected entry %s in the stat dir for domain test", e)
		}
	}

	if err := kvmIntel.Task(testDom).Start("test"); err != nil {
		t.Errorf("Start domain failed %v", err)
	}

	if err := kvmIntel.Task(testDom).Stop("test", true); err != nil {
		t.Errorf("Stop domain failed %v", err)
	}

	if err := kvmIntel.Task(testDom).Delete("test"); err != nil {
		t.Errorf("Delete domain failed %v", err)
	}

	if err := kvmIntel.Task(testDom).Cleanup("test"); err != nil {
		t.Errorf("Cleanup domain failed %v", err)
	}

	state, err = os.Open(kvmStateDir)
	if err != nil {
		t.Errorf("can't open stat dir for test domain %v", err)
	}

	names, err = state.Readdirnames(0)
	if err != nil || len(names) != 0 {
		t.Errorf("can't read stat dir for test domain or state dir is not empty after all domains are gone %v", err)
	}
}

func TestCreateDomConfigContainerVNC(t *testing.T) {
	t.Parallel()

	conf, err := os.CreateTemp("/tmp", "config")
	if err != nil {
		t.Errorf("Can't create config file for a domain %v", err)
	}
	defer os.Remove(conf.Name())

	diskConfigs, diskStatuses := qemuDisks()
	// remove the first disk, so that the container disk is the first one, resulting in IsOciContainer being true
	diskConfigs = diskConfigs[1:]
	diskStatuses = diskStatuses[1:]

	config, aa := domainConfigAndAssignableAdapters(diskConfigs)
	// enable VNC and VNC for shim VM
	config.VmConfig.EnableVnc = true
	config.VmConfig.EnableVncShimVM = true
	if err := kvmIntel.CreateDomConfig(DefaultDomainName, config, types.DomainStatus{},
		diskStatuses, &aa, nil, swtpmCtrlSock, conf); err != nil {
		t.Errorf("CreateDomConfig failed %v", err)
	}
	defer os.Truncate(conf.Name(), 0)

	result, err := os.ReadFile(conf.Name())
	if err != nil {
		t.Errorf("reading conf file failed %v", err)
	}

	result = setStaticVsockCid(result)
	if string(result) != domConfigContainerVNC() {
		t.Errorf("got an unexpected resulting config %s", string(result))
	}
}

func expectedMultifunctionDevice() string {
	return `
[device "pci.0"]
  driver = "pcie-root-port"
  port = "10"
  chassis = "0"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x0"

[device]
  driver = "vfio-pci"
  host = "00:0a.0"
  bus = "pci.0"
  addr = "0x0"

[device "pci.1"]
  driver = "pcie-root-port"
  port = "11"
  chassis = "1"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x1"

[device "pcie-bridge.1"]
  driver = "pcie-pci-bridge"
  bus = "pci.1"
  addr = "0x0"

[device]
  driver = "vfio-pci"
  host = "00:0d.0"
  bus = "pcie-bridge.1"
  addr = "0x1"

[device "pci.2"]
  driver = "pcie-root-port"
  port = "12"
  chassis = "2"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x2"

[device]
  driver = "vfio-pci"
  host = "00:0b.0"
  bus = "pci.2"
  addr = "0x0"

[device]
  driver = "vfio-pci"
  host = "00:0d.2"
  bus = "pcie-bridge.1"
  addr = "0x2"
`
}

func TestPCIAssignmentsTemplateFillMultifunctionDevice(t *testing.T) {
	pciAssignments := []pciDevice{
		{
			ioBundle: types.IoBundle{
				PciLong: "0000:00:0a.0",
				Type:    0,
			},
		},
		{
			ioBundle: types.IoBundle{
				PciLong: "0000:00:0d.0",
				Type:    0,
			},
		},
		{
			ioBundle: types.IoBundle{
				PciLong: "0000:00:0b.0",
				Type:    0,
			},
		},
		{
			ioBundle: types.IoBundle{
				PciLong: "0000:00:0d.2",
				Type:    0,
			},
		},
	}

	wr := bytes.Buffer{}
	multifunctionDevices := multifunctionDevGroup(pciAssignments)
	addrAllocator := pciAddressAllocator{
		pciAssignments:       pciAssignments,
		multifunctionDevices: multifunctionDevices,
	}
	if err := addrAllocator.allocate(); err != nil {
		t.Error(err)
	}

	p := pciAssignmentsTemplateFiller{
		multifunctionDevices: multifunctionDevices,
		file:                 &wr,
	}
	p.do(pciAssignments)

	if wr.String() != expectedMultifunctionDevice() {
		t.Fatalf("not equal, diff: \n%s\ncomplete:\n%s", cmp.Diff(wr.String(), expectedMultifunctionDevice()), wr.String())
	}
}

func TestConvertToMultifunctionPCIDevices(t *testing.T) {
	pciAssignments := []pciDevice{
		{
			ioBundle: types.IoBundle{
				PciLong: "0000:00:0d.0",
				Type:    0,
			},
		},
		{
			ioBundle: types.IoBundle{
				PciLong: "0000:00:aa.8",
				Type:    0,
			},
		},
		{
			ioBundle: types.IoBundle{
				PciLong: "0000:00:0d.2",
				Type:    0,
			},
		},
		{
			ioBundle: types.IoBundle{
				PciLong: "0000:00:0d.f",
				Type:    0,
			},
		},
	}

	mds := multifunctionDevGroup(pciAssignments)

	if len(mds) != 2 {
		t.Fatalf("expected two multifunction pci assignments, but got %d", len(mds))
	}

	t.Log(mds)
	for i, pci := range []string{"0000:00:0d.0", "0000:00:0d.2", "0000:00:0d.f"} {
		functionPCIDev := mds["0000:00:0d"].devs[i].ioBundle.PciLong
		if functionPCIDev != pci {
			t.Logf("expected %s got %s", pci, functionPCIDev)
			t.Fail()
		}
	}

	if len(mds["0000:00:aa"].devs) != 1 {
		t.Fatal("expected one device")
	}
}

func TestPCIAddressAllocator(t *testing.T) {
	g := NewGomegaWithT(t)
	virtualNetworksFunc := func() []virtualNetwork {
		return []virtualNetwork{
			{
				VifConfig: types.VifConfig{
					Bridge:   "br1",
					Vif:      "nbu1x1",
					Mac:      net.HardwareAddr{0x02, 0x16, 0x3e, 0x00, 0x00, 0x01},
					MTU:      1500,
					VifOrder: 1,
				},
				networkID: 0,
			},
			{
				VifConfig: types.VifConfig{
					Bridge:   "br2",
					Vif:      "nbu2x1",
					Mac:      net.HardwareAddr{0x02, 0x16, 0x3e, 0x00, 0x00, 0x02},
					MTU:      1500,
					VifOrder: 4,
				},
				networkID: 1,
			},
		}
	}

	virtualNetworks := virtualNetworksFunc()

	pciAssignmentsFunc := func() []pciDevice {
		return []pciDevice{
			{
				ioBundle: types.IoBundle{
					PciLong: "0000:06:00.0",
					Type:    types.IoNetEth,
				},
				netIntfOrder: 2,
			},
			{
				ioBundle: types.IoBundle{
					PciLong: "0000:00:15.0",
					Type:    types.IoUSBController,
				},
			},
			{
				ioBundle: types.IoBundle{
					PciLong: "0000:06:00.2",
					Type:    types.IoOther,
				},
			},
			{
				ioBundle: types.IoBundle{
					PciLong: "0000:06:00.1",
					Type:    types.IoNetEth,
				},
				netIntfOrder: 3,
			},
			{
				ioBundle: types.IoBundle{
					PciLong: "0000:08:00.0",
					Type:    types.IoNetWWAN,
				},
				netIntfOrder: 0,
			},
		}
	}
	pciAssignments := pciAssignmentsFunc()
	multifunctionDevices := multifunctionDevGroup(pciAssignments)
	g.Expect(multifunctionDevices).To(HaveLen(3))
	addrAllocator := pciAddressAllocator{
		pciAssignments:       pciAssignments,
		virtualNetworks:      virtualNetworks,
		multifunctionDevices: multifunctionDevices,
		firstFreePCIID:       5,
		// First test the legacy order.
		enforceNetInterfaceOrder: false,
	}
	err := addrAllocator.allocate()
	g.Expect(err).ToNot(HaveOccurred())

	g.Expect(virtualNetworks[0].pciDeviceID).To(Equal(5))
	g.Expect(virtualNetworks[1].pciDeviceID).To(Equal(6))
	g.Expect(pciAssignments[0].pciBridgeID).To(Equal(7))
	g.Expect(pciAssignments[0].pciDeviceID).To(Equal(1))
	g.Expect(pciAssignments[1].pciBridgeID).To(Equal(0))
	g.Expect(pciAssignments[1].pciDeviceID).To(Equal(8))
	g.Expect(pciAssignments[2].pciBridgeID).To(Equal(7))
	g.Expect(pciAssignments[2].pciDeviceID).To(Equal(2))
	g.Expect(pciAssignments[3].pciBridgeID).To(Equal(7))
	g.Expect(pciAssignments[3].pciDeviceID).To(Equal(3))
	g.Expect(pciAssignments[4].pciBridgeID).To(Equal(0))
	g.Expect(pciAssignments[4].pciDeviceID).To(Equal(9))

	// Check generated config with the legacy order.
	buffer := bytes.Buffer{}
	vnFiller := virtNetworkTemplateFiller{
		file: &buffer,
	}
	err = vnFiller.do(virtualNetworks, types.HVM)
	g.Expect(err).ToNot(HaveOccurred())
	paFiller := pciAssignmentsTemplateFiller{
		multifunctionDevices: multifunctionDevices,
		file:                 &buffer,
	}
	err = paFiller.do(pciAssignments)
	g.Expect(err).ToNot(HaveOccurred())
	expectedConfig := `
[device "pci.5"]
  driver = "pcie-root-port"
  port = "15"
  chassis = "5"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x5"

[netdev "hostnet0"]
  type = "tap"
  ifname = "nbu1x1"
  br = "br1"
  script = "/etc/xen/scripts/qemu-ifup"
  downscript = "no"
  vhost = "on"

[device "net0"]
  driver = "virtio-net-pci"
  netdev = "hostnet0"
  mac = "02:16:3e:00:00:01"
  bus = "pci.5"
  addr = "0x0"
  host_mtu = "1500"

[device "pci.6"]
  driver = "pcie-root-port"
  port = "16"
  chassis = "6"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x6"

[netdev "hostnet1"]
  type = "tap"
  ifname = "nbu2x1"
  br = "br2"
  script = "/etc/xen/scripts/qemu-ifup"
  downscript = "no"
  vhost = "on"

[device "net1"]
  driver = "virtio-net-pci"
  netdev = "hostnet1"
  mac = "02:16:3e:00:00:02"
  bus = "pci.6"
  addr = "0x0"
  host_mtu = "1500"

[device "pci.7"]
  driver = "pcie-root-port"
  port = "17"
  chassis = "7"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x7"

[device "pcie-bridge.7"]
  driver = "pcie-pci-bridge"
  bus = "pci.7"
  addr = "0x0"

[device]
  driver = "vfio-pci"
  host = "06:00.0"
  bus = "pcie-bridge.7"
  addr = "0x1"

[device "pci.8"]
  driver = "pcie-root-port"
  port = "18"
  chassis = "8"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x8"

[device]
  driver = "vfio-pci"
  host = "00:15.0"
  bus = "pci.8"
  addr = "0x0"

[device]
  driver = "vfio-pci"
  host = "06:00.2"
  bus = "pcie-bridge.7"
  addr = "0x2"

[device]
  driver = "vfio-pci"
  host = "06:00.1"
  bus = "pcie-bridge.7"
  addr = "0x3"

[device "pci.9"]
  driver = "pcie-root-port"
  port = "19"
  chassis = "9"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x9"

[device]
  driver = "vfio-pci"
  host = "08:00.0"
  bus = "pci.9"
  addr = "0x0"
`
	g.Expect(buffer.String()).To(Equal(expectedConfig))

	virtualNetworks = virtualNetworksFunc()
	pciAssignments = pciAssignmentsFunc()
	multifunctionDevices = multifunctionDevGroup(pciAssignments)
	addrAllocator = pciAddressAllocator{
		pciAssignments:           pciAssignments,
		virtualNetworks:          virtualNetworks,
		multifunctionDevices:     multifunctionDevices,
		firstFreePCIID:           5,
		enforceNetInterfaceOrder: true,
	}
	paFiller = pciAssignmentsTemplateFiller{
		multifunctionDevices: multifunctionDevices,
		file:                 &buffer,
	}
	err = addrAllocator.allocate()
	g.Expect(err).ToNot(HaveOccurred())

	g.Expect(virtualNetworks[0].pciDeviceID).To(Equal(6))
	g.Expect(virtualNetworks[1].pciDeviceID).To(Equal(8))
	g.Expect(pciAssignments[0].pciBridgeID).To(Equal(7))
	g.Expect(pciAssignments[0].pciDeviceID).To(Equal(1))
	g.Expect(pciAssignments[1].pciBridgeID).To(Equal(0))
	g.Expect(pciAssignments[1].pciDeviceID).To(Equal(9))
	g.Expect(pciAssignments[2].pciBridgeID).To(Equal(7))
	g.Expect(pciAssignments[2].pciDeviceID).To(Equal(3))
	g.Expect(pciAssignments[3].pciBridgeID).To(Equal(7))
	g.Expect(pciAssignments[3].pciDeviceID).To(Equal(2))
	g.Expect(pciAssignments[4].pciBridgeID).To(Equal(0))
	g.Expect(pciAssignments[4].pciDeviceID).To(Equal(5))

	// Check generated config with the user-defined order.
	buffer.Reset()
	err = vnFiller.do(virtualNetworks, types.HVM)
	g.Expect(err).ToNot(HaveOccurred())
	err = paFiller.do(pciAssignments)
	g.Expect(err).ToNot(HaveOccurred())
	expectedConfig = `
[device "pci.6"]
  driver = "pcie-root-port"
  port = "16"
  chassis = "6"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x6"

[netdev "hostnet0"]
  type = "tap"
  ifname = "nbu1x1"
  br = "br1"
  script = "/etc/xen/scripts/qemu-ifup"
  downscript = "no"
  vhost = "on"

[device "net0"]
  driver = "virtio-net-pci"
  netdev = "hostnet0"
  mac = "02:16:3e:00:00:01"
  bus = "pci.6"
  addr = "0x0"
  host_mtu = "1500"

[device "pci.8"]
  driver = "pcie-root-port"
  port = "18"
  chassis = "8"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x8"

[netdev "hostnet1"]
  type = "tap"
  ifname = "nbu2x1"
  br = "br2"
  script = "/etc/xen/scripts/qemu-ifup"
  downscript = "no"
  vhost = "on"

[device "net1"]
  driver = "virtio-net-pci"
  netdev = "hostnet1"
  mac = "02:16:3e:00:00:02"
  bus = "pci.8"
  addr = "0x0"
  host_mtu = "1500"

[device "pci.7"]
  driver = "pcie-root-port"
  port = "17"
  chassis = "7"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x7"

[device "pcie-bridge.7"]
  driver = "pcie-pci-bridge"
  bus = "pci.7"
  addr = "0x0"

[device]
  driver = "vfio-pci"
  host = "06:00.0"
  bus = "pcie-bridge.7"
  addr = "0x1"

[device "pci.9"]
  driver = "pcie-root-port"
  port = "19"
  chassis = "9"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x9"

[device]
  driver = "vfio-pci"
  host = "00:15.0"
  bus = "pci.9"
  addr = "0x0"

[device]
  driver = "vfio-pci"
  host = "06:00.2"
  bus = "pcie-bridge.7"
  addr = "0x3"

[device]
  driver = "vfio-pci"
  host = "06:00.1"
  bus = "pcie-bridge.7"
  addr = "0x2"

[device "pci.5"]
  driver = "pcie-root-port"
  port = "15"
  chassis = "5"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x5"

[device]
  driver = "vfio-pci"
  host = "08:00.0"
  bus = "pci.5"
  addr = "0x0"
`
	g.Expect(buffer.String()).To(Equal(expectedConfig))

	// Try re-ordering functions of a multifunction device. This should be allowed.
	pciAssignments[0].netIntfOrder = 3
	pciAssignments[3].netIntfOrder = 2
	err = addrAllocator.allocate()
	g.Expect(err).ToNot(HaveOccurred())

	g.Expect(virtualNetworks[0].pciDeviceID).To(Equal(6))
	g.Expect(virtualNetworks[1].pciDeviceID).To(Equal(8))
	g.Expect(pciAssignments[0].pciBridgeID).To(Equal(7))
	g.Expect(pciAssignments[0].pciDeviceID).To(Equal(2)) // 1 -> 2
	g.Expect(pciAssignments[1].pciBridgeID).To(Equal(0))
	g.Expect(pciAssignments[1].pciDeviceID).To(Equal(9))
	g.Expect(pciAssignments[2].pciBridgeID).To(Equal(7))
	g.Expect(pciAssignments[2].pciDeviceID).To(Equal(3))
	g.Expect(pciAssignments[3].pciBridgeID).To(Equal(7))
	g.Expect(pciAssignments[3].pciDeviceID).To(Equal(1)) // 2 -> 1
	g.Expect(pciAssignments[4].pciBridgeID).To(Equal(0))
	g.Expect(pciAssignments[4].pciDeviceID).To(Equal(5))

	// Try to put virtual interface in-between functions of a multifunction device.
	// This should not be allowed.
	virtualNetworks[1].VifOrder = 3
	pciAssignments[0].netIntfOrder = 4

	err = addrAllocator.allocate()
	g.Expect(err).To(HaveOccurred())
	g.Expect(err.Error()).To(ContainSubstring("Invalid VIF nbu2x1 configuration: " +
		"user-defined network interface order disrupts the function sequence " +
		"of the multifunction PCI device 0000:06:00"))
	// Revert the invalid config change.
	virtualNetworks[1].VifOrder = 4
	pciAssignments[0].netIntfOrder = 3
	err = addrAllocator.allocate()
	g.Expect(err).ToNot(HaveOccurred())

	// Try to put PCI-passthrough network device in-between functions of a multifunction
	// device. This should not be allowed.
	pciAssignments[4].netIntfOrder = 3
	pciAssignments[0].netIntfOrder = 4

	err = addrAllocator.allocate()
	g.Expect(err).To(HaveOccurred())
	fmt.Println(err.Error())
	g.Expect(err.Error()).To(ContainSubstring("User-defined network interface order " +
		"disrupts the function sequence of the multifunction PCI devices 0000:06:00 and 0000:08:00"))
}

type PciDeviceJSON struct {
	// netIntfOrder is only applied to network devices when EnforceNetworkInterfaceOrder
	// is enabled.
	NetIntfOrder uint32

	IoBundle types.IoBundle

	// pciBridgeID and pciDeviceID are set by pciAddressAllocator.

	// PCI bridge is only used for multifunction PCI devices.
	// In that case pciBridgeID is address of the bridge on the root bus, while
	// pciDeviceID is device address inside the secondary bus provided by the bridge.
	// For single-function PCI devices, bridge is unused, pciBridgeID is unset
	// and pciDeviceID points to device address on the root bus.
	PciBridgeID int
	PciDeviceID int
}

type PCIAddressAllocatorJSON struct {
	PCIAssignments  []PciDeviceJSON
	VirtualNetworks []struct {
		types.VifConfig
		NetworkID   int
		PciDeviceID int
	}
	MultifunctionDevices map[string]*struct {
		BridgeBus string
		Devs      []*PciDeviceJSON
	}
	FirstFreePCIID           int
	EnforceNetInterfaceOrder bool
}

func (paaj *PCIAddressAllocatorJSON) pciAddressAllocator() pciAddressAllocator {
	a := pciAddressAllocator{}

	a.enforceNetInterfaceOrder = paaj.EnforceNetInterfaceOrder
	a.firstFreePCIID = paaj.FirstFreePCIID

	if paaj.PCIAssignments != nil {
		a.pciAssignments = make([]pciDevice, 0, len(paaj.PCIAssignments))
		for _, pa := range paaj.PCIAssignments {
			// Mirror production (addNoDuplicatePCI in Construct...): the same PCI
			// address is never assigned twice, so sameDevice/index is unambiguous.
			a.pciAssignments = addNoDuplicatePCI(a.pciAssignments, pciDevice{
				netIntfOrder: pa.NetIntfOrder,
				ioBundle:     pa.IoBundle,
				pciBridgeID:  pa.PciBridgeID,
				pciDeviceID:  pa.PciDeviceID,
			})
		}
	}

	if paaj.VirtualNetworks != nil {
		a.virtualNetworks = make([]virtualNetwork, 0, len(paaj.VirtualNetworks))
		for _, vn := range paaj.VirtualNetworks {
			a.virtualNetworks = append(a.virtualNetworks, virtualNetwork{
				VifConfig:   vn.VifConfig,
				networkID:   vn.NetworkID,
				pciDeviceID: vn.PciDeviceID,
			})
		}
	}

	// Build the multifunction-device map the way the production code does, so its
	// entries alias a.pciAssignments (rather than the independent copies the JSON
	// field would yield). This mirrors runtime behavior - in particular it lets
	// convertToInterfaceOrder's updates to netIntfOrder show through the map - and
	// it avoids spurious mismatches from a map that is inconsistent with the
	// assignments (which cannot happen at runtime). The PCIAssignments field is the
	// single source of truth; paaj.MultifunctionDevices is intentionally ignored.
	a.multifunctionDevices = multifunctionDevGroup(a.pciAssignments)

	return a
}

// fuzzMFDJSON and fuzzVNetJSON are type aliases for the anonymous element types
// used inside PCIAddressAllocatorJSON. Because they are aliases (not new defined
// types) they are identical to the field types, so the seed-building helpers
// below can return values that are directly assignable to those fields.
type fuzzMFDJSON = struct {
	BridgeBus string
	Devs      []*PciDeviceJSON
}

type fuzzVNetJSON = struct {
	types.VifConfig
	NetworkID   int
	PciDeviceID int
}

// fuzzPciLongWOFunc returns the PCI long address without the function suffix,
// reusing the production logic so that seed grouping stays in sync with
// multifunctionDevGroup.
func fuzzPciLongWOFunc(pciLong string) string {
	d := pciDevice{ioBundle: types.IoBundle{PciLong: pciLong}}
	woFunc, _ := d.pciLongWOFunction()
	return woFunc
}

// fuzzGroupMFD groups PCI assignments into the multifunction-device map exactly
// the way multifunctionDevGroup does at runtime. This matters because a device
// that is missing from this map is skipped by both allocateLegacy and allocate -
// so without it a seed would never actually exercise the allocator.
func fuzzGroupMFD(pcis []PciDeviceJSON) map[string]*fuzzMFDJSON {
	mds := map[string]*fuzzMFDJSON{}
	for i := range pcis {
		key := fuzzPciLongWOFunc(pcis[i].IoBundle.PciLong)
		if mds[key] == nil {
			mds[key] = &fuzzMFDJSON{}
		}
		dev := pcis[i]
		mds[key].Devs = append(mds[key].Devs, &dev)
	}
	return mds
}

// fuzzPci builds a single PCI-assignment seed entry.
func fuzzPci(pciLong string, ioType types.IoType, netIntfOrder uint32) PciDeviceJSON {
	return PciDeviceJSON{
		NetIntfOrder: netIntfOrder,
		IoBundle: types.IoBundle{
			PciLong: pciLong,
			Type:    ioType,
		},
	}
}

// fuzzVNet builds a single virtual-network seed entry.
func fuzzVNet(vif string, vifOrder uint32) fuzzVNetJSON {
	v := fuzzVNetJSON{}
	v.Vif = vif
	v.VifOrder = vifOrder
	return v
}

// fuzzSeed assembles an allocator seed, deriving the multifunction-device map
// from the PCI assignments the same way the production code path does.
func fuzzSeed(firstFree int, vnets []fuzzVNetJSON, pcis []PciDeviceJSON) PCIAddressAllocatorJSON {
	return PCIAddressAllocatorJSON{
		FirstFreePCIID:       firstFree,
		VirtualNetworks:      vnets,
		PCIAssignments:       pcis,
		MultifunctionDevices: fuzzGroupMFD(pcis),
	}
}

// fuzzSeedNoMFD is like fuzzSeed but deliberately omits the multifunction-device
// map, so that the PCI assignments are skipped by both allocators. It exercises
// the "missing multifunctionDevices entry" path alongside virtual-network
// allocation.
func fuzzSeedNoMFD(firstFree int, vnets []fuzzVNetJSON, pcis []PciDeviceJSON) PCIAddressAllocatorJSON {
	return PCIAddressAllocatorJSON{
		FirstFreePCIID:  firstFree,
		VirtualNetworks: vnets,
		PCIAssignments:  pcis,
	}
}

func FuzzInterfaceLegacyOrderConversion(f *testing.F) {
	// The seed corpus only provides starting points for the fuzzer to mutate.
	// convertToInterfaceOrder reproduces the legacy layout only for network
	// interfaces, so the fuzz body skips any config that contains a non-network PCI
	// device (allocate places those after the network ones regardless of order). The
	// seeds are a spread of shapes - virtual networks, single- and multi-function
	// devices, varying firstFreePCIID; those with non-network devices are simply
	// skipped at run time.
	seeds := []PCIAddressAllocatorJSON{
		// Empty / minimal allocators (nothing to order).
		{},
		fuzzSeed(0, []fuzzVNetJSON{}, []PciDeviceJSON{}),

		// A single PCI assignment with no matching multifunction entry: both
		// allocators must skip it (covers the "missing entry" path).
		{PCIAssignments: []PciDeviceJSON{{}}},
		fuzzSeedNoMFD(3,
			[]fuzzVNetJSON{fuzzVNet("eth0", 1)},
			[]PciDeviceJSON{fuzzPci("0000:06:00.0", types.IoNetEth, 1)}),

		// Virtual networks only, in ascending VifOrder.
		fuzzSeed(5, []fuzzVNetJSON{fuzzVNet("eth0", 1)}, nil),
		fuzzSeed(5, []fuzzVNetJSON{fuzzVNet("eth0", 1), fuzzVNet("eth1", 2)}, nil),
		fuzzSeed(0, []fuzzVNetJSON{
			fuzzVNet("eth0", 1), fuzzVNet("eth1", 2), fuzzVNet("eth2", 3),
		}, nil),

		// Single-function PCI assignments (each a bridge-less device).
		fuzzSeed(4, nil, []PciDeviceJSON{fuzzPci("0000:06:00.0", types.IoNetEth, 1)}),
		fuzzSeed(4, nil, []PciDeviceJSON{fuzzPci("0000:00:15.0", types.IoUSBController, 0)}),
		fuzzSeed(5, nil, []PciDeviceJSON{
			fuzzPci("0000:06:00.0", types.IoNetEth, 1),
			fuzzPci("0000:08:00.0", types.IoNetWWAN, 2),
		}),
		fuzzSeed(5, nil, []PciDeviceJSON{
			fuzzPci("0000:06:00.0", types.IoOther, 0),
			fuzzPci("0000:08:00.0", types.IoUSBController, 0),
		}),

		// Multifunction devices (several functions sharing one bridge).
		fuzzSeed(5, nil, []PciDeviceJSON{
			fuzzPci("0000:06:00.0", types.IoNetEth, 1),
			fuzzPci("0000:06:00.1", types.IoNetEth, 2),
		}),
		fuzzSeed(5, nil, []PciDeviceJSON{
			fuzzPci("0000:06:00.0", types.IoNetEth, 1),
			fuzzPci("0000:06:00.1", types.IoOther, 0),
		}),
		fuzzSeed(5, nil, []PciDeviceJSON{
			fuzzPci("0000:06:00.0", types.IoNetEth, 1),
			fuzzPci("0000:06:00.1", types.IoNetEth, 2),
			fuzzPci("0000:06:00.2", types.IoNetEth, 3),
		}),

		// Mixed virtual networks + PCI assignments in natural order.
		fuzzSeed(5,
			[]fuzzVNetJSON{fuzzVNet("eth0", 1)},
			[]PciDeviceJSON{fuzzPci("0000:06:00.0", types.IoNetEth, 5)}),
		fuzzSeed(5,
			[]fuzzVNetJSON{fuzzVNet("eth0", 1), fuzzVNet("eth1", 2)},
			[]PciDeviceJSON{
				fuzzPci("0000:06:00.0", types.IoNetEth, 3),
				fuzzPci("0000:06:00.1", types.IoNetEth, 4),
				fuzzPci("0000:08:00.0", types.IoNetWWAN, 5),
				fuzzPci("0000:00:15.0", types.IoUSBController, 0),
				fuzzPci("0000:0a:00.0", types.IoOther, 0),
			}),

		// Larger firstFreePCIID offset.
		fuzzSeed(12,
			[]fuzzVNetJSON{fuzzVNet("eth0", 1)},
			[]PciDeviceJSON{fuzzPci("0000:06:00.0", types.IoNetEth, 2)}),

		// Empty PciLong maps to a degenerate group key, so the device is still
		// allocated rather than skipped (exercises that edge of pciLongWOFunction).
		fuzzSeed(5, nil, []PciDeviceJSON{fuzzPci("", types.IoNetEth, 1)}),
	}

	for _, seed := range seeds {
		bs, err := json.Marshal(seed)
		if err != nil {
			f.Fatalf("could not marshal seed example: %v", err)
		}
		f.Log(string(bs))
		f.Add(string(bs))
	}

	f.Fuzz(func(t *testing.T, allocatorJSON string) {
		var aj PCIAddressAllocatorJSON
		err := json.Unmarshal([]byte(allocatorJSON), &aj)
		if err != nil {
			return
		}
		aLegacy := aj.pciAddressAllocator()
		aLegacy.enforceNetInterfaceOrder = false

		aNew := aj.pciAddressAllocator()
		aNew.enforceNetInterfaceOrder = false

		aLegacy.allocateLegacy()
		aNew.allocate()

		// convertToInterfaceOrder (run by allocate in the legacy case) rewrites the
		// interface-order fields, so compare the allocated PCI addresses rather than
		// the whole struct: both allocators must place every VIF and PCI device at
		// the same address.
		for i := range aLegacy.virtualNetworks {
			if aLegacy.virtualNetworks[i].pciDeviceID != aNew.virtualNetworks[i].pciDeviceID {
				t.Fatalf("VIF #%d address mismatch for %s:\nlegacy=%d vs new=%d",
					i, allocatorJSON, aLegacy.virtualNetworks[i].pciDeviceID,
					aNew.virtualNetworks[i].pciDeviceID)
			}
		}
		for i := range aLegacy.pciAssignments {
			if aLegacy.pciAssignments[i].pciBridgeID != aNew.pciAssignments[i].pciBridgeID ||
				aLegacy.pciAssignments[i].pciDeviceID != aNew.pciAssignments[i].pciDeviceID {
				t.Fatalf("PCI device #%d (%s) address mismatch for %s:\n"+
					"legacy=(bridge %d, dev %d) vs new=(bridge %d, dev %d)",
					i, aLegacy.pciAssignments[i].ioBundle.PciLong, allocatorJSON,
					aLegacy.pciAssignments[i].pciBridgeID, aLegacy.pciAssignments[i].pciDeviceID,
					aNew.pciAssignments[i].pciBridgeID, aNew.pciAssignments[i].pciDeviceID)
			}
		}

		// now let's check if it breaks the contract with ordered nics

		aOrderedStable := aj.pciAddressAllocator()
		aOrderedStable.enforceNetInterfaceOrder = true

		aOrderedNew := aj.pciAddressAllocator()
		aOrderedNew.enforceNetInterfaceOrder = true

		aOrderedStable.allocateContract()
		aOrderedNew.allocate()

		if !reflect.DeepEqual(aOrderedNew, aOrderedStable) {
			t.Fatalf("contract broken between new and stable enforced ordering")
		}
	})

}
func (a *pciAddressAllocator) allocateLegacy() error {
	// Virtual network interfaces precede PCI-passthrough devices in the PCI topology.
	// Among virtual interfaces, the order received from zedagent is preserved.
	pciDeviceID := a.firstFreePCIID
	for i := range a.virtualNetworks {
		a.virtualNetworks[i].pciDeviceID = pciDeviceID
		pciDeviceID++
	}

	// Preserve order of PCI assignments as received from zedagent, but group
	// functions of the same multifunction PCI device under the same bridge.
	pciBridgeIDs := make(map[string]int) // key = PCI address without function suffix
	for i := range a.pciAssignments {
		pciLongWoFunc, err := a.pciAssignments[i].pciLongWOFunction()
		if err != nil {
			logrus.Warnf("retrieving pci address without function failed: %v", err)
			continue
		}
		md := a.multifunctionDevices[pciLongWoFunc]
		if md == nil {
			// Even when device is not multifunction, it still should have entry
			// in the a.multifunctionDevices map.
			logrus.Warnf("missing multifunctionDevices entry for pci address: %s",
				pciLongWoFunc)
			continue
		}
		if len(md.devs) > 1 {
			// Multi-function PCI device.
			pciBridgeID, bridgeIDAllocated := pciBridgeIDs[pciLongWoFunc]
			if !bridgeIDAllocated {
				pciBridgeID = pciDeviceID
				pciBridgeIDs[pciLongWoFunc] = pciBridgeID
				pciDeviceID++
			}
			a.pciAssignments[i].pciBridgeID = pciBridgeID
			// Skip PCI address 0 which is unsupported for standard hotplug controller.
			a.pciAssignments[i].pciDeviceID = md.index(a.pciAssignments[i]) + 1
		} else {
			// Not multifunction PCI device.
			a.pciAssignments[i].pciBridgeID = 0
			a.pciAssignments[i].pciDeviceID = pciDeviceID
			pciDeviceID++
		}
	}
	return nil
}

// allocate sets pciDeviceID and pciBridgeID for every pciDevice and virtualNetwork
// based on user-configured ordering requirements.
func (a *pciAddressAllocator) allocateContract() error {
	if !a.enforceNetInterfaceOrder {
		// Fallback to legacy ordering of PCI devices.
		return a.allocateLegacy()
	}

	// Determine PCI addresses for virtual network interfaces, which are connected
	// to the root bus using root ports.
	for i := range a.virtualNetworks {
		pciDeviceID := a.firstFreePCIID
		// Increment pciDeviceID by 1 for every (virtual or assigned) PCI device
		// which should have lower PCI address.
		// For a multifunction PCI device, we increment by 1 for the entire group of
		// functions, as they share a single address on the root bus through their bridge.
		for j := range a.virtualNetworks {
			if i == j {
				continue
			}
			if a.virtualNetworks[j].VifOrder < a.virtualNetworks[i].VifOrder {
				pciDeviceID++
			}
		}
		for pciAddr, md := range a.multifunctionDevices {
			isBefore, isAfter := md.compareOrderWithVirtNet(a.virtualNetworks[i])
			invalidOrder := isBefore && isAfter
			if invalidOrder {
				return logError("Invalid VIF %s configuration: user-defined network "+
					"interface order disrupts the function sequence of the multifunction "+
					"PCI device %s. Interleaving PCI device functions with other devices "+
					"is not allowed.", a.virtualNetworks[i].Vif, pciAddr)
			}
			if isBefore {
				pciDeviceID++
			}
		}
		a.virtualNetworks[i].pciDeviceID = pciDeviceID
	}

	// Determine PCI addresses for direct PCI assignments.
	for i := range a.pciAssignments {
		pciLongWoFunc, err := a.pciAssignments[i].pciLongWOFunction()
		if err != nil {
			logrus.Warnf("retrieving pci address without function failed: %v", err)
			continue
		}
		md := a.multifunctionDevices[pciLongWoFunc]
		if md == nil {
			// Even when device is not multifunction, it still should have entry
			// in the multifunctionDevices map.
			logrus.Warnf("missing multifunctionDevices entry for pci address: %s",
				pciLongWoFunc)
			continue
		}
		// Increment pciDeviceOrBridgeID by 1 for every (virtual or assigned) PCI device
		// which should have lower PCI address.
		// For a multifunction PCI device, we increment by 1 for the entire group of
		// functions, as they share a single address on the root bus through their bridge.
		pciDeviceOrBridgeID := a.firstFreePCIID
		for _, virtNet := range a.virtualNetworks {
			// Order validity already checked when addresses for virtual networks
			// were determined.
			if isBefore, _ := md.compareOrderWithVirtNet(virtNet); !isBefore {
				// Also increased when order is undefined, i.e. this PCI device
				// does not have network function. Non-networking PCI devices
				// are placed after virtual network interfaces.
				pciDeviceOrBridgeID++
			}
		}
		thisHasNetFunc := md.hasNetworkFunction()
		for pciAddr2, md2 := range a.multifunctionDevices {
			if pciLongWoFunc == pciAddr2 {
				continue
			}
			theOtherHasNetFunc := md2.hasNetworkFunction()
			if !thisHasNetFunc {
				if theOtherHasNetFunc {
					// Network functions take priority in the order.
					pciDeviceOrBridgeID++
				} else {
					// Between non-networking devices, order by PCI addresses
					// lexicographically.
					if pciLongWoFunc > pciAddr2 {
						pciDeviceOrBridgeID++
					}
				}
				continue
			}
			if !theOtherHasNetFunc {
				// The other non-network device is ordered after this network device.
				continue
			}
			// Both devices have at least one network function.
			theOtherIsBefore, theOtherIsAfter := md2.compareOrder(*md)
			invalidOrder := theOtherIsBefore && theOtherIsAfter
			if invalidOrder {
				return logError("User-defined network interface order disrupts "+
					"the function sequence of the multifunction PCI devices %s and %s. "+
					"Interleaving PCI device functions with other devices/functions "+
					"is not allowed.", pciLongWoFunc, pciAddr2)
			}
			if theOtherIsBefore {
				pciDeviceOrBridgeID++
			}
		}
		if len(md.devs) > 1 {
			// pciDeviceOrBridgeID is for the bridge wrt. the root bus.
			a.pciAssignments[i].pciBridgeID = pciDeviceOrBridgeID
			// Determine device address on the secondary bus provided by the bridge.
			// Skip PCI address 0 which is unsupported for standard hotplug controller.
			pciDeviceID := 1
			devIndex := md.index(a.pciAssignments[i])
			thisIsNetDev := a.pciAssignments[i].ioBundle.Type.IsNet()
			for dev2Index, dev2 := range md.devs {
				theOtherIsNetDev := dev2.ioBundle.Type.IsNet()
				if !thisIsNetDev {
					if theOtherIsNetDev {
						// Network functions take priority in the order.
						pciDeviceID++
					} else {
						// Between non-networking functions, preserve the order received
						// from zedagent.
						if devIndex > dev2Index {
							pciDeviceID++
						}
					}
					continue
				}
				if !theOtherIsNetDev {
					// The other non-network device is ordered after this network device.
					continue
				}
				// Both devices are of the networking type.
				if dev2.netIntfOrder < a.pciAssignments[i].netIntfOrder {
					pciDeviceID++
				}
			}
			a.pciAssignments[i].pciDeviceID = pciDeviceID
		} else {
			// Not multifunction PCI device.
			a.pciAssignments[i].pciBridgeID = 0
			a.pciAssignments[i].pciDeviceID = pciDeviceOrBridgeID
		}
	}
	return nil
}
