# syntax=docker/dockerfile-upstream:1.5.0-rc2-labs

FROM ubuntu:latest

ARG UID=1
ARG GID=1

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update
RUN apt-get -y dist-upgrade

RUN apt-get -y install apt-file
RUN apt-file update

RUN apt-get -y install build-essential
RUN apt-get -y install git
RUN apt-get -y install cmake
RUN apt-get -y install pkg-config
RUN apt-get -y install python3-pexpect
RUN apt-get -y install gdb
RUN apt-get -y install libcapnp-dev capnproto
RUN apt-get -y install zlib1g-dev
RUN apt-get -y install vim
RUN apt-get -y install autoconf
RUN apt-get -y install libtool
RUN apt-get -y install udev
RUN apt-get -y install uuid-dev
RUN apt-get -y install libblkid-dev
RUN apt-get -y install libssl-dev
RUN apt-get -y install libtirpc-dev
RUN apt-get -y install strace
RUN apt-get -y install libcap2-bin
RUN apt-get -y install runc
RUN apt-get -y install tmux
RUN apt-get -y install curl
RUN apt-get -y install net-tools
RUN apt-get -y install netcat-traditional
RUN apt-get -y install socat
RUN apt-get -y install jq
RUN apt-get -y install wget
RUN apt-get -y install kitty-terminfo
RUN apt-get -y install sudo
RUN apt-get -y install psmisc
RUN apt-get -y install htop
RUN apt-get -y install lsof
RUN apt-get -y install ninja-build
RUN apt-get -y install ccache
RUN apt-get -y install libzstd-dev
RUN apt-get -y install lldb
RUN apt-get -y install hx

ENV ZFS_VERSION=2.3.3
ENV ZFS_COMMIT=zfs-${ZFS_VERSION}
ENV ZFS_REPO=https://github.com/openzfs/zfs
RUN git clone ${ZFS_REPO} --branch ${ZFS_COMMIT} --single-branch /usr/src/zfs
WORKDIR /usr/src/zfs
RUN ./autogen.sh
RUN ./configure \
    --prefix=/usr \
    --with-tirpc \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --infodir=/usr/share/info \
    --localstatedir=/var \
    --with-config=user \
    --with-udevdir=/lib/udev \
    --disable-systemd \
    --disable-static
RUN ./scripts/make_gitrev.sh
RUN make -j "$(getconf _NPROCESSORS_ONLN)"
RUN make install

WORKDIR /usr/src
RUN git clone https://github.com/rr-debugger/rr.git --single-branch
RUN mkdir -vp /usr/src/rr/build
WORKDIR /usr/src/rr/build
RUN --mount=type=cache,target=/root/.cache/rr-build CMAKE_CXX_COMPILER_LAUNCHER=ccache cmake -DCMAKE_BUILD_TYPE=Release -Ddisable32bit=ON ../
RUN --mount=type=cache,target=/root/.cache/rr-build make -j $(nproc)
RUN make install

RUN git clone https://go.googlesource.com/go /usr/src/go1.4 --branch release-branch.go1.4 --single-branch
WORKDIR /usr/src/go1.4/src
RUN --mount=type=cache,target=/root/.cache/go-build CC="ccache gcc" CGO_ENABLED=0 ./make.bash

RUN git clone https://go.googlesource.com/go /usr/src/go1.17.3 --branch go1.17.3 --single-branch
WORKDIR /usr/src/go1.17.3/src
ENV GOROOT_BOOTSTRAP=/usr/src/go1.4/
RUN --mount=type=cache,target=/root/.cache/go-build ./make.bash
RUN git clone https://go.googlesource.com/go /usr/src/go1.21.6 --branch go1.21.6 --single-branch
WORKDIR /usr/src/go1.21.6/src
ENV GOROOT_BOOTSTRAP=/usr/src/go1.17.3/
RUN --mount=type=cache,target=/root/.cache/go-build ./make.bash

RUN git clone https://go.googlesource.com/go /usr/src/go1.23.6 --branch go1.23.6 --single-branch
WORKDIR /usr/src/go1.23.6/src
ENV GOROOT_BOOTSTRAP=/usr/src/go1.21.6/
RUN --mount=type=cache,target=/root/.cache/go-build ./make.bash

RUN git clone https://go.googlesource.com/go /usr/src/go1.24.6 --branch go1.24.6 --single-branch
WORKDIR /usr/src/go1.24.6/src
ENV GOROOT_BOOTSTRAP=/usr/src/go1.23.6/
RUN --mount=type=cache,target=/root/.cache/go-build ./make.bash

ARG GOVER=1.26.4

RUN git clone https://go.googlesource.com/go /usr/src/go$GOVER --branch go$GOVER --single-branch
WORKDIR /usr/src/go${GOVER}/src
ENV GOROOT_BOOTSTRAP=/usr/src/go1.24.6/
RUN --mount=type=cache,target=/root/.cache/go-build ./make.bash
RUN --mount=type=cache,target=/root/.cache/go-build ./all.bash

ENV PATH="${PATH}:/usr/src/go$GOVER/bin:/root/go/bin"
RUN ln -s /usr/src/go$GOVER/bin/go /usr/bin/go

WORKDIR /usr/src
RUN git clone https://github.com/tinygo-org/tinygo.git
WORKDIR /usr/src/tinygo
RUN git submodule update --init
RUN make llvm-source
RUN --mount=type=cache,target=/root/.cache/ccache,id=tinygo-llvm-build \
    --mount=type=cache,target=/root/.cache/go-build \
	ccache -z && \
	make llvm-build && \
	ccache -s
RUN --mount=type=cache,target=/root/.cache/ccache,id=tinygo-build \
    --mount=type=cache,target=/root/.cache/go-build \
	make -j ${nproc} && make release

WORKDIR /usr/local
RUN tar xf /usr/src/tinygo/build/release.tar.gz
ENV PATH="${PATH}:/usr/local/tinygo/bin"

WORKDIR /usr/src
RUN --mount=type=cache,target=/root/.cache/go-build git clone https://github.com/containerd/containerd.git
WORKDIR /usr/src/containerd
RUN make -j $(nproc)
RUN make install

RUN curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

WORKDIR /usr/src
ADD https://github.com/golang/go.git /usr/src/go-latest

WORKDIR /src
RUN userdel ubuntu
RUN useradd ubuntu -u $UID -d /home/ubuntu
RUN mkdir -p /home/ubuntu
RUN chown ubuntu /home/ubuntu
RUN echo "ubuntu ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
USER $UID:$GID

RUN --mount=type=cache,target=/root/.cache/go-build go install github.com/go-delve/delve/cmd/dlv@latest
RUN --mount=type=cache,target=/root/.cache/go-build go install go.uber.org/nilaway/cmd/nilaway@latest
RUN --mount=type=cache,target=/root/.cache/go-build go install golang.org/x/tools/cmd/callgraph@latest
RUN --mount=type=cache,target=/root/.cache/go-build GOEXPERIMENT=jsonv2 go install github.com/Zxilly/go-size-analyzer/cmd/gsa@latest
RUN --mount=type=cache,target=/root/.cache/go-build go install github.com/kisielk/errcheck@latest
RUN --mount=type=cache,target=/root/.cache/go-build go install golang.org/x/tools/gopls@latest
RUN --mount=type=cache,target=/root/.cache/go-build go install golang.org/x/tools/cmd/deadcode@latest
RUN --mount=type=cache,target=/root/.cache/go-build go install github.com/GaijinEntertainment/go-exhaustruct/v3/cmd/exhaustruct@latest
RUN --mount=type=cache,target=/root/.cache/go-build go install github.com/nametake/golangci-lint-langserver@latest

ENV PATH="${PATH}:/usr/src/go$GOVER/bin:/home/ubuntu/go/bin"

COPY init_ubuntu.sh /

ENTRYPOINT ["/init_ubuntu.sh"]
