// Code generated by "stringer -type=lineType"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[undecided-0]
	_ = x[notComment-1]
	_ = x[isComment-2]
}

const _lineType_name = "undecidednotCommentisComment"

var _lineType_index = [...]uint8{0, 9, 19, 28}

func (i lineType) String() string {
	if i >= lineType(len(_lineType_index)-1) {
		return "lineType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _lineType_name[_lineType_index[i]:_lineType_index[i+1]]
}
