# Copyright (c) 2024 Zededa, Inc.
# SPDX-License-Identifier: Apache-2.0

git-change-exec: actions.go actions-lint.go actions-test.go actions_test.go main.go codeparse.go
	go build

.PHONY: clean

clean:
	rm -fv git-change-exec
